/* Le sette lingue del sito.

   GENERATO — non si corregge qui. La sorgente è `genera-lingue.py` (fuori dal
   repo, nella cartella di lavoro), che rimette insieme due cose diverse:

     · le frasi che esistono NELL'APP — le regole del mare, i versi del
       naufragio, il benvenuto — rilette da Localizable.xcstrings a ogni
       rigenerazione. Sono quelle che si dichiarano ad Apple: se divergessero
       dall'app di una virgola sarebbe un difetto, non una sfumatura;
     · le frasi del solo sito, scritte a mano dentro quello script.

   LA CHIAVE È L'INGLESE DELLA PAGINA, non un codice. Così qui si legge
   l'originale accanto alla traduzione, e se un giorno l'inglese in
   `index.html` cambia, la voce smette semplicemente di combaciare e la
   console lo dice — invece di lasciare una traduzione vecchia attaccata a una
   frase nuova, che è il modo in cui questi file mentono.

   L'inglese non sta qui dentro: sta nell'HTML, ed è quello che legge chi
   arriva senza JavaScript. */
const LINGUE = {
 "it": {
  "Bottlegram — a slow messaging app": "Bottlegram — un'app di messaggi lenti",
  "Skip to content": "Vai al contenuto",
  "The waiting": "L'attesa",
  "The journal": "Il diario",
  "The beaches": "Le spiagge",
  "The chart": "La carta",
  "A slow messaging app": "Un'app di messaggi lenti",
  "The sea has no use for hurry.": "Il mare non sa che farsene della fretta.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Da qualche parte, uno sconosciuto ti sta scrivendo. Nessun nome. Nessun rumore. Solo la marea, e quello che decide di lasciarti sulla sabbia.",
  "Coming to the App Store": "Presto sull'App Store",
  "Not out yet. The sea is still being tested.": "Non è ancora uscita. Il mare è ancora in collaudo.",
  "The shipwreck": "Il naufragio",
  "Sardegna, Italy": "Sardegna, Italia",
  "The point": "Il punto",
  "Everything here is slow,": "Qui è tutto lento,",
  "and none of it is by accident.": "e non è successo per caso.",
  "You write, and then you wait.": "Scrivi, e poi aspetti.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Una lettera ci mette quanto ci mette l'acqua che vi separa. Una riva sullo stesso mare può risponderti entro domattina; dall'altra parte del mondo ti farà aspettare giorni. Non c'è niente da toccare che la faccia arrivare prima — e dopo la prima volta smetti di volerlo.",
  "The beach is empty, and it is yours.": "La spiaggia è vuota, ed è tua.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Nessuno è online. Nessuno è assente. Nessuno sta scrivendo, e niente è segnato come consegnato, visualizzato o letto. C'è una riva, il rumore dell'acqua, e un orizzonte che non ti chiede niente.",
  "You have all the time in the world to choose the words.": "Hai tutto il tempo del mondo per scegliere le parole.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Una lettera che costa qualcosa si scrive meglio. Qui non ne spari sette di fila, non ti correggi un'ora dopo, e non puoi richiamarne indietro nessuna. Così ci stai sopra un po', e dici la cosa vera invece di quella veloce.",
  "And the waiting turns out to be the good part.": "E l'attesa si scopre essere la parte bella.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Passano i giorni. Fai altro. Poi la marea ti lascia sulla sabbia una cosa che nessuno aveva programmato, nessuno aveva sponsorizzato e nessuno avrebbe potuto venderti — la calligrafia di uno sconosciuto, da una costa che non hai mai visto.",
  "Somewhere to go when everything else is shouting.": "Un posto dove andare quando tutto il resto urla.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Qui è mattina e il vento viene da terra. Non ti dirò il mio nome, ma ti dirò che ho piantato tre fichi dietro casa e uno ha attecchito. Se questa bottiglia approda da qualche parte, scrivimi e dimmi che tempo fa da te.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Ogni giorno la marea porterà bottiglie di sconosciuti da tutto il mare. Parla con gentilezza — le parole vanno lontano.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Il mare non sa che farsene della fretta. Scrivi a uno sconosciuto su una spiaggia vera e lascia che la marea ci metta giorni a portarla — niente nomi, niente feed, un'app per iPhone per chi si rivuole indietro l'attesa.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Il mare non sa che farsene della fretta. Scrivi a uno sconosciuto su una spiaggia vera e lascia che la marea ci metta giorni a portarla.",
  "Sections": "Sezioni",
  "A nautical chart with the route of a bottle across the open sea": "Una carta nautica con la rotta di una bottiglia attraverso il mare aperto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "L'app a Cala Goloritzé a mezzogiorno: mare turchese, sabbia chiara e quattro bottiglie approdate sulla riva.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Un carteggio nel diario: la lettera di uno sconosciuto a cui chi legge ha dato in privato il nome «Black sand», sotto la risposta, e un avviso che dice che una loro bottiglia è ancora in mare.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carta nautica: una rotta disegnata da Cala Goloritzé fuori dal Mediterraneo e su per l'Atlantico verso l'Islanda, con la bottiglia a metà strada.",
  "Who you are here": "Chi sei, qui",
  "No name. No face.": "Nessun nome. Nessun volto.",
  "A seal in wax.": "Un sigillo di ceralacca.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Ogni naufrago imprime sempre lo stesso emblema nella cera — e su questo mare quello è tutto di una persona: nessun profilo, nessuna fotografia, nessuno storico, niente da andare a cercare dopo. Uno sconosciuto, una riva, e la sua calligrafia.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Può darsi che ti scrivano in una lingua che non hai mai letto. Un tocco la porta nella tua; un altro rimette le loro parole com'erano, esattamente come le hanno scritte.",
  "What you keep": "Quello che conservi",
  "A correspondence, not a chat.": "Un carteggio, non una chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Qui le lettere non scorrono via. Restano in un diario di carta, nell'ordine in cui il mare le ha consegnate — le tue da una parte, le loro dall'altra, ognuna con sotto il giorno in cui è approdata.",
  "You may give a stranger a private name, only for your own pages:": "A uno sconosciuto puoi dare un nome privato, solo per le tue pagine:",
  "the lighthouse keeper": "il guardiano del faro",
  "the girl with the boat": "la ragazza con la barca",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Loro non lo sapranno mai. E quando una loro bottiglia è ancora in mare, il diario lo dice e basta, e ti chiede di aspettare.",
  "The tide keeps its own time — and while you are here, so do you.": "La marea ha un suo tempo — e finché sei qui, ce l'hai anche tu.",
  "Where you wake up": "Dove ti svegli",
  "A real beach, at the end of the world.": "Una spiaggia vera, in capo al mondo.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Tratti di costa veri alle loro coordinate vere — e la luce che ci sta sopra è quella della tua ora: aprila a mezzanotte e la tua spiaggia è buia, con le stelle sull'acqua. Nessuna di queste è una fotografia. Ogni onda la disegna l'app, linea per linea.",
  "The shore": "La riva",
  "The hour": "L'ora",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "Guardati intorno. Sulle spiagge artiche, di notte, l'aurora passa sopra la testa.",
  "The crossing": "La traversata",
  "You can watch it go.": "Puoi guardarla andare.",
  "your shore": "la tua riva",
  "still at sea": "ancora in mare",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Una bottiglia che hai lanciato lascia una linea sulla carta, e la linea cresce mentre dormi. Il tratto pieno è la distanza già navigata; il tratteggio davanti compare solo quando sai chi aspetta dall'altra parte.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Le isole degli sconosciuti di cui hai letto le lettere restano segnate per sempre — una mappa privata di tutti quelli che il mare ti ha presentato.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carta è tutta dell'app: coste da Natural Earth, di pubblico dominio, portate dentro. Nessun servizio di mappe viene mai chiamato, e niente di dove sei esce dalle tue mani.",
  "Before you go": "Prima di andare",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "In fondo a ogni lettera aperta c'è «Riferisci al Mare». Il carteggio si chiude, e la lettera non torna sulla tua sabbia. Con lo stesso gesto puoi bloccare chi l'ha scritta: la marea non vi rimetterà più insieme, né in un verso né nell'altro.",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "Per una segnalazione urgente, un problema o una domanda qualsiasi, questo indirizzo arriva a una persona vera:",
  "A bottle, thrown well, can reach anyone.": "Una bottiglia, lanciata bene, può raggiungere chiunque.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Coste da Natural Earth (pubblico dominio). Suoni da freesound.org (CC0). Nessun servizio di mappe, nessun tracciamento, nessun cookie: questa pagina non sa chi sei, esattamente come il mare.",
  "Map": "Mappa",
  "Journal": "Diario",
  "Throw": "Lancia",
  "Emporium": "Emporio",
  "Mediterranean": "Mediterraneo",
  "Tropical": "Tropicale",
  "Arctic": "Artico",
  "Volcanic": "Vulcanico",
  "Wild Atlantic": "Atlantico selvaggio",
  "Dawn": "Alba",
  "Day": "Giorno",
  "Dusk": "Tramonto",
  "Night": "Notte",
  "The storm took the ship, the cargo, and every map you owned.": "La tempesta si è presa la nave, il carico e ogni mappa che possedevi.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "Il mare, in cambio, ti ha lasciato una cosa sola: una spiaggia in capo al mondo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dicono che la marea porti parole di altri naufraghi. E che una bottiglia, lanciata bene, possa raggiungere chiunque.",
  "Your new home": "La tua nuova casa",
  "A stranger": "Uno sconosciuto",
  "The rules of the sea": "Le regole del mare",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "Qui si scrive a sconosciuti, e uno sconosciuto merita la stessa cortesia di un vicino. Queste sono le poche regole che tengono questo mare abitabile.",
  "The sea tolerates none of this": "Il mare non tollera nulla di tutto questo",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "Molestie, insulti, minacce, odio o discriminazione, contenuti sessuali, spam e truffe. Tolleranza zero: una lettera così esce dal mare, e chi la scrive può essere bandito dalla sua spiaggia — anche alla prima volta.",
  "Any letter can be reported to the Sea": "Ogni lettera si può riferire al Mare",
  "Someone looks, within a day": "Qualcuno guarda, entro un giorno",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "Ogni segnalazione viene letta da una persona entro 24 ore. La lettera può essere tolta dal mare e chi l'ha scritta bandito.",
  "Stay a stranger": "Resta uno sconosciuto",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "Nessuno qui sa chi sei, ed è meglio così: non scrivere il tuo cognome, il tuo indirizzo, il tuo numero o i tuoi profili. Una lettera parte e non si richiama.",
  "Writing to whoever keeps the lighthouse": "Scrivere a chi tiene il faro"
 },
 "es": {
  "Bottlegram — a slow messaging app": "Bottlegram — una app de mensajes lentos",
  "Skip to content": "Ir al contenido",
  "The waiting": "La espera",
  "The journal": "El diario",
  "The beaches": "Las playas",
  "The chart": "La carta náutica",
  "A slow messaging app": "Una app de mensajes lentos",
  "The sea has no use for hurry.": "Al mar no le sirve de nada la prisa.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "En algún lugar, un desconocido te está escribiendo. Sin nombres. Sin ruido. Solo la marea, y lo que decida dejarte en la arena.",
  "Coming to the App Store": "Pronto en la App Store",
  "Not out yet. The sea is still being tested.": "Todavía no ha salido. El mar aún se está probando.",
  "The shipwreck": "El naufragio",
  "Sardegna, Italy": "Cerdeña, Italia",
  "The point": "El porqué",
  "Everything here is slow,": "Aquí todo es lento,",
  "and none of it is by accident.": "y nada de ello es casualidad.",
  "You write, and then you wait.": "Escribes, y luego esperas.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Una carta tarda lo que tarde el agua que os separa. Una orilla del mismo mar puede responder por la mañana; el otro extremo del mundo te hará esperar días. No hay nada que puedas tocar para que llegue antes, y después de la primera dejas de quererlo.",
  "The beach is empty, and it is yours.": "La playa está vacía, y es tuya.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Nadie está en línea. Nadie está ausente. Nadie está escribiendo, y nada aparece como entregado, visto o leído. Hay una orilla, el sonido del agua y un horizonte que no te pide nada.",
  "You have all the time in the world to choose the words.": "Tienes todo el tiempo del mundo para elegir las palabras.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Una carta que cuesta algo se escribe mejor. Aquí no soltarás siete seguidas, no te corregirás una hora después y no puedes retirar ninguna. Así que te quedas un rato con ella, y dices lo verdadero en lugar de lo rápido.",
  "And the waiting turns out to be the good part.": "Y resulta que la espera es lo mejor.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Pasan los días. Haces otras cosas. Entonces la marea deja en tu arena algo que nadie programó, nadie promocionó y nadie podría haberte vendido: la letra de un desconocido, desde una costa que nunca has visto.",
  "Somewhere to go when everything else is shouting.": "Un sitio al que ir cuando todo lo demás grita.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Aquí es de mañana y el viento viene de tierra. No te diré mi nombre, pero sí que planté tres higueras detrás de la casa y una prendió. Si esta botella llega a alguna parte, escríbeme y dime qué tiempo hace donde estás.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Cada día la marea traerá botellas de desconocidos de todo el mar. Habla con amabilidad: las palabras llegan lejos.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Al mar no le sirve de nada la prisa. Escribe a un desconocido en una playa de verdad y deja que la marea tarde días en llevarla: sin nombres, sin feeds, una app de iPhone para quien quiere recuperar la espera.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Al mar no le sirve de nada la prisa. Escribe a un desconocido en una playa de verdad y deja que la marea tarde días en llevarla.",
  "Sections": "Secciones",
  "A nautical chart with the route of a bottle across the open sea": "Una carta náutica con la ruta de una botella a través del mar abierto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "La app en Cala Goloritzé a mediodía: mar turquesa, arena clara y cuatro botellas llegadas a la orilla.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Una correspondencia en el diario: la carta de un desconocido a quien quien lee ha llamado en privado «Black sand», debajo la respuesta, y un aviso de que una botella suya sigue en el mar.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carta náutica: una ruta trazada desde Cala Goloritzé fuera del Mediterráneo y hacia el norte por el Atlántico rumbo a Islandia, con la botella a medio camino.",
  "Who you are here": "Quién eres aquí",
  "No name. No face.": "Sin nombre. Sin rostro.",
  "A seal in wax.": "Un sello de lacre.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Cada náufrago imprime siempre el mismo emblema en el lacre, y en este mar eso es toda una persona: sin perfil, sin fotografía, sin historial, sin nada que buscar después. Un desconocido, una orilla y su letra.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Puede que te escriban en una lengua que nunca has leído. Un toque la convierte en la tuya; otro devuelve sus palabras tal como las escribieron.",
  "What you keep": "Lo que conservas",
  "A correspondence, not a chat.": "Una correspondencia, no un chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Aquí las cartas no se van con el desplazamiento. Se quedan en un diario de papel, en el orden en que el mar las entregó: las tuyas de un lado, las suyas del otro, cada una con el día en que llegó a la orilla escrito debajo.",
  "You may give a stranger a private name, only for your own pages:": "A un desconocido puedes darle un nombre privado, solo para tus páginas:",
  "the lighthouse keeper": "el farero",
  "the girl with the boat": "la chica de la barca",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Ellos nunca lo sabrán. Y cuando una botella suya sigue en el agua, el diario lo dice sin más, y te pide que esperes.",
  "The tide keeps its own time — and while you are here, so do you.": "La marea lleva su propio tiempo, y mientras estés aquí, tú también.",
  "Where you wake up": "Dónde te despiertas",
  "A real beach, at the end of the world.": "Una playa de verdad, en el fin del mundo.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Tramos de costa reales en sus coordenadas reales, y la luz que los baña es la de tu propia hora: ábrela a medianoche y tu playa está a oscuras, con las estrellas sobre el agua. Ninguna de estas es una fotografía. Cada ola la dibuja la app, línea a línea.",
  "The shore": "La orilla",
  "The hour": "La hora",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "Echa un vistazo. En las playas árticas, de noche, la aurora pasa por encima.",
  "The crossing": "La travesía",
  "You can watch it go.": "Puedes verla marchar.",
  "your shore": "tu orilla",
  "still at sea": "aún en el mar",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Una botella que has lanzado deja una línea en la carta, y la línea crece mientras duermes. El trazo continuo es la distancia ya navegada; los guiones de delante solo aparecen cuando sabes quién espera al otro extremo.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Las islas de los desconocidos cuyas cartas has leído quedan marcadas para siempre: un mapa privado de todos los que el mar te ha presentado.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carta es de la propia app: costas de Natural Earth, de dominio público, llevadas dentro. Nunca se llama a ningún servicio de mapas, y nada sobre dónde estás sale de tus manos.",
  "Before you go": "Antes de irte",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "Al pie de cada carta abierta está «Informar al Mar». La correspondencia se cierra y la carta no vuelve a tu arena. Con el mismo gesto puedes bloquear a quien la escribió: la marea no volverá a reuniros, en ninguna dirección.",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "Para un aviso urgente, un problema o cualquier duda, esta dirección llega a una persona de verdad:",
  "A bottle, thrown well, can reach anyone.": "Una botella, bien lanzada, puede llegar a cualquiera.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Costas de Natural Earth (dominio público). Sonidos de freesound.org (CC0). Sin servicio de mapas, sin rastreo, sin cookies: esta página no sabe quién eres, igual que el mar.",
  "Map": "Mapa",
  "Journal": "Diario",
  "Throw": "Lanza",
  "Emporium": "Emporio",
  "Mediterranean": "Mediterráneo",
  "Tropical": "Tropical",
  "Arctic": "Ártico",
  "Volcanic": "Volcánico",
  "Wild Atlantic": "Atlántico salvaje",
  "Dawn": "Amanecer",
  "Day": "Día",
  "Dusk": "Ocaso",
  "Night": "Noche",
  "The storm took the ship, the cargo, and every map you owned.": "La tormenta se llevó el barco, la carga y todos los mapas que tenías.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "El mar, a cambio, te dejó una sola cosa: una playa en el fin del mundo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dicen que la marea trae palabras de otros náufragos. Y que una botella, bien lanzada, puede llegar a cualquiera.",
  "Your new home": "Tu nuevo hogar",
  "A stranger": "Un desconocido",
  "The rules of the sea": "Las reglas del mar",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "Aquí escribes a desconocidos, y un desconocido merece la misma cortesía que un vecino. Estas son las pocas reglas que mantienen habitable este mar.",
  "The sea tolerates none of this": "El mar no tolera nada de esto",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "Acoso, insultos, amenazas, odio o discriminación, contenido sexual, spam y estafas. Tolerancia cero: una carta así sale del mar, y quien la escribe puede ser desterrado de su playa, incluso a la primera.",
  "Any letter can be reported to the Sea": "Cualquier carta puede informarse al Mar",
  "Someone looks, within a day": "Alguien lo revisa en menos de un día",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "Cada aviso lo lee una persona en un plazo de 24 horas. La carta puede retirarse del mar y su autor ser desterrado.",
  "Stay a stranger": "Sigue siendo un desconocido",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "Nadie aquí sabe quién eres, y es mejor así: no escribas tu apellido, tu dirección, tu número ni tus perfiles. Una carta zarpa y no se puede llamar de vuelta.",
  "Writing to whoever keeps the lighthouse": "Escribir a quien cuida el faro"
 },
 "fr": {
  "Bottlegram — a slow messaging app": "Bottlegram — une messagerie lente",
  "Skip to content": "Aller au contenu",
  "The waiting": "L'attente",
  "The journal": "Le journal",
  "The beaches": "Les plages",
  "The chart": "La carte",
  "A slow messaging app": "Une messagerie lente",
  "The sea has no use for hurry.": "La mer n'a que faire de la hâte.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Quelque part, un inconnu vous écrit. Aucun nom. Aucun bruit. Rien que la marée, et ce qu'elle décide de laisser sur votre sable.",
  "Coming to the App Store": "Bientôt sur l'App Store",
  "Not out yet. The sea is still being tested.": "Pas encore sortie. La mer est encore à l'essai.",
  "The shipwreck": "Le naufrage",
  "Sardegna, Italy": "Sardaigne, Italie",
  "The point": "L'essentiel",
  "Everything here is slow,": "Ici tout est lent,",
  "and none of it is by accident.": "et rien de tout cela n'est un hasard.",
  "You write, and then you wait.": "Vous écrivez, puis vous attendez.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Une lettre met le temps que met l'eau qui vous sépare. Un rivage sur la même mer répondra peut-être au matin ; l'autre bout du monde vous fera attendre des jours. Rien de ce que vous toucherez ne la fera venir plus tôt — et après la première, vous cessez de le souhaiter.",
  "The beach is empty, and it is yours.": "La plage est vide, et elle est à vous.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Personne n'est en ligne. Personne n'est absent. Personne n'est en train d'écrire, et rien n'est marqué distribué, vu ou lu. Il y a un rivage, le bruit de l'eau, et un horizon qui ne vous demande rien.",
  "You have all the time in the world to choose the words.": "Vous avez tout le temps du monde pour choisir les mots.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Une lettre qui coûte quelque chose s'écrit mieux. Ici vous n'en enverrez pas sept d'affilée, vous ne vous corrigerez pas une heure plus tard, et vous ne pouvez en rappeler aucune. Alors vous restez un moment avec elle, et vous dites la chose vraie plutôt que la chose rapide.",
  "And the waiting turns out to be the good part.": "Et l'attente se révèle être le meilleur.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Les jours passent. Vous faites autre chose. Puis la marée laisse sur votre sable quelque chose que personne n'avait programmé, que personne n'avait promu et que personne n'aurait pu vous vendre — l'écriture d'un inconnu, venue d'une côte que vous n'avez jamais vue.",
  "Somewhere to go when everything else is shouting.": "Un endroit où aller quand tout le reste crie.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Ici c'est le matin et le vent vient de la terre. Je ne vous dirai pas mon nom, mais je vous dirai que j'ai planté trois figuiers derrière la maison et que l'un d'eux a pris. Si cette bouteille aborde quelque part, écrivez-moi le temps qu'il fait chez vous.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Chaque jour, la marée apportera des bouteilles d'inconnus de toute la mer. Parlez avec douceur — les mots vont loin.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "La mer n'a que faire de la hâte. Écrivez à un inconnu sur une vraie plage et laissez la marée mettre des jours à l'emporter — aucun nom, aucun fil, une application iPhone pour qui veut retrouver l'attente.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "La mer n'a que faire de la hâte. Écrivez à un inconnu sur une vraie plage et laissez la marée mettre des jours à l'emporter.",
  "Sections": "Sections",
  "A nautical chart with the route of a bottle across the open sea": "Une carte marine avec la route d'une bouteille en pleine mer",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "L'application à Cala Goloritzé à midi : mer turquoise, sable clair et quatre bouteilles échouées sur le rivage.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Une correspondance dans le journal : la lettre d'un inconnu que le lecteur a nommé en privé « Black sand », la réponse en dessous, et une note indiquant qu'une de leurs bouteilles est encore en mer.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carte marine : une route tracée depuis Cala Goloritzé, hors de la Méditerranée et vers le nord à travers l'Atlantique en direction de l'Islande, la bouteille à mi-parcours.",
  "Who you are here": "Qui vous êtes ici",
  "No name. No face.": "Pas de nom. Pas de visage.",
  "A seal in wax.": "Un sceau de cire.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Chaque naufragé imprime toujours le même emblème dans la cire — et sur cette mer, c'est là tout un être : pas de profil, pas de photographie, pas d'historique, rien à aller chercher ensuite. Un inconnu, un rivage, et son écriture.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Ils vous écrivent peut-être dans une langue que vous n'avez jamais lue. Une touche la met dans la vôtre ; une autre remet leurs mots exactement comme ils les ont écrits.",
  "What you keep": "Ce que vous gardez",
  "A correspondence, not a chat.": "Une correspondance, pas une conversation.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Ici, les lettres ne défilent pas au loin. Elles restent dans un journal de papier, dans l'ordre où la mer les a remises — les vôtres d'un côté, les leurs de l'autre, chacune avec, en dessous, le jour où elle a abordé.",
  "You may give a stranger a private name, only for your own pages:": "Vous pouvez donner à un inconnu un nom privé, rien que pour vos pages :",
  "the lighthouse keeper": "le gardien du phare",
  "the girl with the boat": "la fille au bateau",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Ils ne le sauront jamais. Et lorsqu'une de leurs bouteilles est encore sur l'eau, le journal le dit simplement, et vous demande d'attendre.",
  "The tide keeps its own time — and while you are here, so do you.": "La marée a son propre temps — et tant que vous êtes ici, vous aussi.",
  "Where you wake up": "Où vous vous réveillez",
  "A real beach, at the end of the world.": "Une vraie plage, au bout du monde.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. De vraies portions de côte à leurs vraies coordonnées — et la lumière qui les baigne est celle de votre propre heure : ouvrez à minuit et votre plage est sombre, les étoiles au-dessus de l'eau. Aucune n'est une photographie. Chaque vague est dessinée par l'application, trait par trait.",
  "The shore": "Le rivage",
  "The hour": "L'heure",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "Regardez autour de vous. Sur les plages arctiques, la nuit, l'aurore passe au-dessus.",
  "The crossing": "La traversée",
  "You can watch it go.": "Vous pouvez la regarder s'en aller.",
  "your shore": "votre rivage",
  "still at sea": "encore en mer",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Une bouteille que vous avez lancée laisse une ligne sur la carte, et la ligne grandit pendant votre sommeil. Le trait plein est la distance déjà parcourue ; les pointillés devant n'apparaissent qu'une fois que vous savez qui attend à l'autre bout.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Les îles des inconnus dont vous avez lu les lettres restent marquées pour de bon — une carte privée de tous ceux que la mer vous a présentés.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carte appartient à l'application : côtes issues de Natural Earth, domaine public, embarquées avec elle. Aucun service cartographique n'est jamais appelé, et rien de votre position ne quitte vos mains.",
  "Before you go": "Avant de partir",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "Au bas de chaque lettre ouverte se trouve « Signaler à la Mer ». La correspondance se ferme, et la lettre ne revient pas sur votre sable. Du même geste, vous pouvez bloquer son auteur : la marée ne vous réunira plus jamais, dans aucun sens.",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "Pour un signalement urgent, un problème ou n'importe quelle question, cette adresse atteint une personne réelle :",
  "A bottle, thrown well, can reach anyone.": "Une bouteille, bien lancée, peut atteindre n'importe qui.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Côtes issues de Natural Earth (domaine public). Sons de freesound.org (CC0). Aucun service cartographique, aucun traçage, aucun cookie : cette page ne sait pas qui vous êtes, exactement comme la mer.",
  "Map": "Carte",
  "Journal": "Journal",
  "Throw": "Lance",
  "Emporium": "Emporium",
  "Mediterranean": "Méditerranée",
  "Tropical": "Tropical",
  "Arctic": "Arctique",
  "Volcanic": "Volcanique",
  "Wild Atlantic": "Atlantique sauvage",
  "Dawn": "Aube",
  "Day": "Jour",
  "Dusk": "Crépuscule",
  "Night": "Nuit",
  "The storm took the ship, the cargo, and every map you owned.": "La tempête a pris le navire, la cargaison et toutes les cartes que tu possédais.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "La mer, en échange, ne t'a laissé qu'une chose : une plage au bout du monde.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "On dit que la marée porte les mots d'autres naufragés. Et qu'une bouteille, bien lancée, peut atteindre n'importe qui.",
  "Your new home": "Ton nouveau chez-toi",
  "A stranger": "Un inconnu",
  "The rules of the sea": "Les règles de la mer",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "Ici, on écrit à des inconnus, et un inconnu mérite la même courtoisie qu'un voisin. Voici les quelques règles qui gardent cette mer habitable.",
  "The sea tolerates none of this": "La mer ne tolère rien de tout cela",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "Harcèlement, insultes, menaces, haine ou discrimination, contenu sexuel, spam et arnaques. Tolérance zéro : une telle lettre est retirée de la mer, et son auteur peut être banni de sa plage — dès la première fois.",
  "Any letter can be reported to the Sea": "Toute lettre peut être signalée à la Mer",
  "Someone looks, within a day": "Quelqu'un regarde, sous un jour",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "Chaque signalement est lu par une personne sous 24 heures. La lettre peut être retirée de la mer et son auteur banni.",
  "Stay a stranger": "Reste un inconnu",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "Personne ici ne sait qui tu es, et c'est mieux ainsi : n'écris pas ton nom de famille, ton adresse, ton numéro ni tes profils. Une lettre part et ne se rappelle pas.",
  "Writing to whoever keeps the lighthouse": "Écrire à celui qui garde le phare"
 },
 "de": {
  "Bottlegram — a slow messaging app": "Bottlegram — langsame Nachrichten",
  "Skip to content": "Zum Inhalt springen",
  "The waiting": "Das Warten",
  "The journal": "Das Tagebuch",
  "The beaches": "Die Strände",
  "The chart": "Die Seekarte",
  "A slow messaging app": "Langsame Nachrichten",
  "The sea has no use for hurry.": "Das Meer weiß mit Eile nichts anzufangen.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Irgendwo da draußen schreibt Ihnen ein Fremder. Keine Namen. Kein Lärm. Nur die Gezeiten und das, was sie in Ihrem Sand zurücklassen.",
  "Coming to the App Store": "Bald im App Store",
  "Not out yet. The sea is still being tested.": "Noch nicht erschienen. Das Meer wird noch erprobt.",
  "The shipwreck": "Der Schiffbruch",
  "Sardegna, Italy": "Sardinien, Italien",
  "The point": "Worum es geht",
  "Everything here is slow,": "Hier ist alles langsam,",
  "and none of it is by accident.": "und nichts davon ist ein Versehen.",
  "You write, and then you wait.": "Sie schreiben, und dann warten Sie.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Ein Brief braucht so lange, wie das Wasser zwischen Ihnen braucht. Eine Küste am selben Meer antwortet vielleicht bis zum Morgen; die andere Seite der Welt lässt Sie Tage warten. Kein Tippen bringt ihn früher — und nach dem ersten Mal wollen Sie es gar nicht mehr.",
  "The beach is empty, and it is yours.": "Der Strand ist leer, und er gehört Ihnen.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Niemand ist online. Niemand ist abwesend. Niemand tippt, und nichts ist als zugestellt, gesehen oder gelesen markiert. Es gibt ein Ufer, das Geräusch des Wassers und einen Horizont, der nichts von Ihnen will.",
  "You have all the time in the world to choose the words.": "Sie haben alle Zeit der Welt, die Worte zu wählen.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Ein Brief, der etwas kostet, wird besser geschrieben. Hier feuern Sie nicht sieben hintereinander ab, korrigieren sich nicht eine Stunde später und können keinen zurückholen. Also bleiben Sie eine Weile dabei und sagen das Wahre statt des Schnellen.",
  "And the waiting turns out to be the good part.": "Und das Warten stellt sich als das Schönste heraus.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Tage vergehen. Sie tun anderes. Dann lässt die Flut etwas in Ihrem Sand zurück, das niemand geplant, niemand beworben und niemand Ihnen hätte verkaufen können — die Handschrift eines Fremden, von einer Küste, die Sie nie gesehen haben.",
  "Somewhere to go when everything else is shouting.": "Ein Ort für die Zeiten, in denen alles andere schreit.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Hier ist Morgen und der Wind kommt vom Land. Ich nenne Ihnen meinen Namen nicht, aber ich sage Ihnen, dass ich hinter dem Haus drei Feigenbäume gepflanzt habe und einer angewachsen ist. Wenn diese Flasche irgendwo anlandet, schreiben Sie mir, wie das Wetter bei Ihnen ist.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Jeden Tag bringt die Flut Flaschen von Fremden aus dem ganzen Meer. Sprechen Sie freundlich — Worte reisen weit.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Das Meer weiß mit Eile nichts anzufangen. Schreiben Sie einem Fremden an einem wirklichen Strand und lassen Sie die Flut Tage dafür brauchen — keine Namen, keine Feeds, eine iPhone-App für alle, die das Warten zurückwollen.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Das Meer weiß mit Eile nichts anzufangen. Schreiben Sie einem Fremden an einem wirklichen Strand und lassen Sie die Flut Tage dafür brauchen.",
  "Sections": "Abschnitte",
  "A nautical chart with the route of a bottle across the open sea": "Eine Seekarte mit der Route einer Flasche über das offene Meer",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "Die App an der Cala Goloritzé zur Mittagszeit: türkisfarbenes Meer, heller Sand und vier angespülte Flaschen.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Ein Briefwechsel im Tagebuch: der Brief eines Fremden, den die lesende Person im Stillen „Black sand“ genannt hat, darunter die Antwort und ein Hinweis, dass eine Flasche von ihnen noch auf See ist.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "Die Seekarte: eine Route von der Cala Goloritzé aus dem Mittelmeer hinaus und nordwärts über den Atlantik Richtung Island, die Flasche auf halbem Weg.",
  "Who you are here": "Wer Sie hier sind",
  "No name. No face.": "Kein Name. Kein Gesicht.",
  "A seal in wax.": "Ein Siegel in Wachs.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Jeder Schiffbrüchige drückt stets dasselbe Emblem ins Wachs — und auf diesem Meer ist das ein ganzer Mensch: kein Profil, kein Foto, keine Chronik, nichts zum Nachschlagen. Ein Fremder, ein Ufer und seine Handschrift.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Vielleicht schreibt man Ihnen in einer Sprache, die Sie nie gelesen haben. Ein Tippen macht sie zu Ihrer; ein weiteres stellt die eigenen Worte wieder her, genau so, wie sie geschrieben wurden.",
  "What you keep": "Was bleibt",
  "A correspondence, not a chat.": "Ein Briefwechsel, kein Chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Hier scrollen Briefe nicht davon. Sie bleiben in einem Tagebuch aus Papier, in der Reihenfolge, in der das Meer sie brachte — Ihre auf der einen Seite, ihre auf der anderen, jeder mit dem Tag darunter, an dem er anlandete.",
  "You may give a stranger a private name, only for your own pages:": "Einem Fremden dürfen Sie einen eigenen Namen geben, nur für Ihre Seiten:",
  "the lighthouse keeper": "der Leuchtturmwärter",
  "the girl with the boat": "das Mädchen mit dem Boot",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Sie werden es nie erfahren. Und wenn eine Flasche von ihnen noch auf dem Wasser ist, sagt das Tagebuch es einfach und bittet Sie zu warten.",
  "The tide keeps its own time — and while you are here, so do you.": "Die Gezeiten haben ihre eigene Zeit — und solange Sie hier sind, haben Sie sie auch.",
  "Where you wake up": "Wo Sie aufwachen",
  "A real beach, at the end of the world.": "Ein wirklicher Strand, am Ende der Welt.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Echte Küstenstücke an ihren echten Koordinaten — und das Licht darauf ist das Ihrer eigenen Stunde: öffnen Sie um Mitternacht, und Ihr Strand ist dunkel, die Sterne über dem Wasser. Keines davon ist eine Fotografie. Jede Welle zeichnet die App, Strich für Strich.",
  "The shore": "Das Ufer",
  "The hour": "Die Stunde",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "Sehen Sie sich um. An arktischen Stränden zieht nachts das Polarlicht über Sie hinweg.",
  "The crossing": "Die Überfahrt",
  "You can watch it go.": "Sie können ihr nachsehen.",
  "your shore": "Ihr Ufer",
  "still at sea": "noch auf See",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Eine geworfene Flasche hinterlässt eine Linie auf der Karte, und die Linie wächst, während Sie schlafen. Der durchgezogene Teil ist die bereits gesegelte Strecke; die Striche voraus erscheinen erst, wenn Sie wissen, wer am anderen Ende wartet.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Die Inseln der Fremden, deren Briefe Sie gelesen haben, bleiben für immer eingezeichnet — eine private Karte all jener, die das Meer Ihnen vorgestellt hat.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "Die Karte gehört der App selbst: Küstenlinien von Natural Earth, gemeinfrei, im Programm mitgeführt. Kein Kartendienst wird je aufgerufen, und nichts über Ihren Standort verlässt Ihre Hände.",
  "Before you go": "Bevor Sie gehen",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "Am Fuß jedes geöffneten Briefes steht „Dem Meer melden“. Der Briefwechsel schließt sich, und der Brief kehrt nicht in Ihren Sand zurück. Mit derselben Geste können Sie den Verfasser sperren: Die Flut wird Sie nie wieder zusammenbringen, in keine Richtung.",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "Für eine dringende Meldung, ein Problem oder irgendeine Frage erreicht diese Adresse einen echten Menschen:",
  "A bottle, thrown well, can reach anyone.": "Eine gut geworfene Flasche kann jeden erreichen.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Küstenlinien von Natural Earth (gemeinfrei). Klänge von freesound.org (CC0). Kein Kartendienst, kein Tracking, keine Cookies: Diese Seite weiß nicht, wer Sie sind — genau wie das Meer.",
  "Map": "Karte",
  "Journal": "Tagebuch",
  "Throw": "Wirf",
  "Emporium": "Kontor",
  "Mediterranean": "Mittelmeer",
  "Tropical": "Tropen",
  "Arctic": "Arktis",
  "Volcanic": "Vulkanisch",
  "Wild Atlantic": "Wilder Atlantik",
  "Dawn": "Morgengrauen",
  "Day": "Tag",
  "Dusk": "Dämmerung",
  "Night": "Nacht",
  "The storm took the ship, the cargo, and every map you owned.": "Der Sturm nahm das Schiff, die Ladung und jede Karte, die du besaßest.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "Das Meer ließ dir dafür nur eines: einen Strand am Ende der Welt.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Man sagt, die Flut trage Worte anderer Schiffbrüchiger. Und dass eine gut geworfene Flasche jeden erreichen kann.",
  "Your new home": "Dein neues Zuhause",
  "A stranger": "Jemand Unbekanntes",
  "The rules of the sea": "Die Regeln des Meeres",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "Hier schreibst du an Fremde, und ein Fremder verdient dieselbe Höflichkeit wie ein Nachbar. Dies sind die wenigen Regeln, die dieses Meer bewohnbar halten.",
  "The sea tolerates none of this": "Das Meer duldet nichts davon",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "Belästigung, Beleidigungen, Drohungen, Hass oder Diskriminierung, sexuelle Inhalte, Spam und Betrug. Null Toleranz: Ein solcher Brief wird aus dem Meer genommen, und wer ihn schrieb, kann von seinem Strand verbannt werden — schon beim ersten Mal.",
  "Any letter can be reported to the Sea": "Jeder Brief kann dem Meer gemeldet werden",
  "Someone looks, within a day": "Jemand sieht es sich an, binnen eines Tages",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "Jede Meldung wird binnen 24 Stunden von einem Menschen gelesen. Der Brief kann aus dem Meer genommen und sein Verfasser verbannt werden.",
  "Stay a stranger": "Bleib ein Fremder",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "Niemand hier weiß, wer du bist, und das ist gut so: Schreibe nicht deinen Nachnamen, deine Adresse, deine Nummer oder deine Profile. Ein Brief fährt aus und lässt sich nicht zurückrufen.",
  "Writing to whoever keeps the lighthouse": "An die Person schreiben, die den Leuchtturm hütet"
 },
 "pt-BR": {
  "Bottlegram — a slow messaging app": "Bottlegram — um app de mensagens lentas",
  "Skip to content": "Ir para o conteúdo",
  "The waiting": "A espera",
  "The journal": "O diário",
  "The beaches": "As praias",
  "The chart": "A carta náutica",
  "A slow messaging app": "Um app de mensagens lentas",
  "The sea has no use for hurry.": "O mar não tem uso para a pressa.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Em algum lugar, um desconhecido está escrevendo para você. Sem nomes. Sem barulho. Só a maré, e o que ela decidir deixar na sua areia.",
  "Coming to the App Store": "Em breve na App Store",
  "Not out yet. The sea is still being tested.": "Ainda não saiu. O mar ainda está em testes.",
  "The shipwreck": "O naufrágio",
  "Sardegna, Italy": "Sardenha, Itália",
  "The point": "O ponto",
  "Everything here is slow,": "Aqui tudo é lento,",
  "and none of it is by accident.": "e nada disso é por acaso.",
  "You write, and then you wait.": "Você escreve, e então espera.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Uma carta demora o que demorar a água entre vocês. Uma praia no mesmo mar pode responder pela manhã; o outro lado do mundo vai fazer você esperar dias. Não há nada em que tocar para que chegue antes — e depois da primeira, você para de querer isso.",
  "The beach is empty, and it is yours.": "A praia está vazia, e é sua.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Ninguém está on-line. Ninguém está ausente. Ninguém está digitando, e nada é marcado como entregue, visto ou lido. Há uma praia, o som da água e um horizonte que não pede nada de você.",
  "You have all the time in the world to choose the words.": "Você tem todo o tempo do mundo para escolher as palavras.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Uma carta que custa alguma coisa é mais bem escrita. Aqui você não dispara sete seguidas, não se corrige uma hora depois e não pode chamar nenhuma de volta. Então você fica um tempo com ela, e diz o que é verdadeiro em vez do que é rápido.",
  "And the waiting turns out to be the good part.": "E a espera acaba sendo a melhor parte.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Os dias passam. Você faz outras coisas. Então a maré deixa na sua areia algo que ninguém programou, ninguém promoveu e ninguém poderia ter vendido para você — a letra de um desconhecido, de uma costa que você nunca viu.",
  "Somewhere to go when everything else is shouting.": "Um lugar para ir quando todo o resto está gritando.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Aqui é manhã e o vento vem da terra. Não vou dizer meu nome, mas vou dizer que plantei três figueiras atrás de casa e uma pegou. Se esta garrafa chegar a algum lugar, escreva e me conte que tempo faz aí.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Todo dia a maré vai trazer garrafas de desconhecidos de todo o mar. Fale com gentileza — as palavras vão longe.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "O mar não tem uso para a pressa. Escreva para um desconhecido numa praia de verdade e deixe a maré levar dias para entregar — sem nomes, sem feeds, um app de iPhone para quem quer a espera de volta.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "O mar não tem uso para a pressa. Escreva para um desconhecido numa praia de verdade e deixe a maré levar dias para entregar.",
  "Sections": "Seções",
  "A nautical chart with the route of a bottle across the open sea": "Uma carta náutica com a rota de uma garrafa pelo mar aberto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "O app em Cala Goloritzé ao meio-dia: mar turquesa, areia clara e quatro garrafas na praia.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Uma correspondência no diário: a carta de um desconhecido a quem quem lê deu em particular o nome «Black sand», a resposta abaixo, e um aviso de que uma garrafa dele ainda está no mar.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "A carta náutica: uma rota traçada de Cala Goloritzé para fora do Mediterrâneo e ao norte pelo Atlântico rumo à Islândia, com a garrafa no meio do caminho.",
  "Who you are here": "Quem você é aqui",
  "No name. No face.": "Sem nome. Sem rosto.",
  "A seal in wax.": "Um selo de lacre.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Cada náufrago imprime sempre o mesmo emblema no lacre — e neste mar isso é uma pessoa inteira: sem perfil, sem fotografia, sem histórico, nada para procurar depois. Um desconhecido, uma praia e a letra dele.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Pode ser que escrevam para você numa língua que você nunca leu. Um toque a transforma na sua; outro devolve as palavras deles exatamente como foram escritas.",
  "What you keep": "O que você guarda",
  "A correspondence, not a chat.": "Uma correspondência, não um chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Aqui as cartas não somem com a rolagem. Elas ficam num diário de papel, na ordem em que o mar as entregou — as suas de um lado, as dele do outro, cada uma com o dia em que chegou escrito embaixo.",
  "You may give a stranger a private name, only for your own pages:": "Você pode dar a um desconhecido um nome particular, só para as suas páginas:",
  "the lighthouse keeper": "o faroleiro",
  "the girl with the boat": "a moça do barco",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Eles nunca vão saber. E quando uma garrafa deles ainda está na água, o diário simplesmente diz isso, e pede que você espere.",
  "The tide keeps its own time — and while you are here, so do you.": "A maré tem o tempo dela — e enquanto você estiver aqui, você também tem.",
  "Where you wake up": "Onde você acorda",
  "A real beach, at the end of the world.": "Uma praia de verdade, no fim do mundo.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Trechos de costa reais nas coordenadas reais — e a luz sobre eles é a da sua própria hora: abra à meia-noite e a sua praia está escura, com as estrelas sobre a água. Nenhuma delas é uma fotografia. Cada onda é desenhada pelo app, linha por linha.",
  "The shore": "A praia",
  "The hour": "A hora",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "Dê uma olhada. Nas praias árticas, à noite, a aurora passa lá em cima.",
  "The crossing": "A travessia",
  "You can watch it go.": "Você pode vê-la partir.",
  "your shore": "sua praia",
  "still at sea": "ainda no mar",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Uma garrafa que você lançou deixa uma linha na carta, e a linha cresce enquanto você dorme. O traço cheio é a distância já navegada; os tracejados à frente só aparecem quando você sabe quem espera do outro lado.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "As ilhas dos desconhecidos cujas cartas você leu ficam marcadas para sempre — um mapa particular de todos que o mar apresentou a você.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "A carta é do próprio app: costas do Natural Earth, de domínio público, carregadas dentro dele. Nenhum serviço de mapas é chamado, e nada sobre onde você está sai das suas mãos.",
  "Before you go": "Antes de ir",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "No pé de cada carta aberta há «Relatar ao Mar». A correspondência se encerra, e a carta não volta para a sua areia. No mesmo gesto você pode bloquear quem a escreveu: a maré nunca mais vai juntar vocês, em nenhuma direção.",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "Para um aviso urgente, um problema ou qualquer dúvida, este endereço chega a uma pessoa de verdade:",
  "A bottle, thrown well, can reach anyone.": "Uma garrafa, bem lançada, pode alcançar qualquer um.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Costas do Natural Earth (domínio público). Sons do freesound.org (CC0). Sem serviço de mapas, sem rastreamento, sem cookies: esta página não sabe quem você é, exatamente como o mar.",
  "Map": "Mapa",
  "Journal": "Diário",
  "Throw": "Lance",
  "Emporium": "Empório",
  "Mediterranean": "Mediterrâneo",
  "Tropical": "Tropical",
  "Arctic": "Ártico",
  "Volcanic": "Vulcânico",
  "Wild Atlantic": "Atlântico selvagem",
  "Dawn": "Amanhecer",
  "Day": "Dia",
  "Dusk": "Anoitecer",
  "Night": "Noite",
  "The storm took the ship, the cargo, and every map you owned.": "A tempestade levou o navio, a carga e todos os mapas que você tinha.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "O mar, em troca, deixou uma coisa só: uma praia no fim do mundo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dizem que a maré traz palavras de outros náufragos. E que uma garrafa, bem lançada, pode alcançar qualquer um.",
  "Your new home": "Seu novo lar",
  "A stranger": "Um desconhecido",
  "The rules of the sea": "As regras do mar",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "Aqui você escreve a desconhecidos, e um desconhecido merece a mesma cortesia que um vizinho. Estas são as poucas regras que mantêm este mar habitável.",
  "The sea tolerates none of this": "O mar não tolera nada disso",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "Assédio, insultos, ameaças, ódio ou discriminação, conteúdo sexual, spam e golpes. Tolerância zero: uma carta assim sai do mar, e quem a escreveu pode ser banido de sua praia — mesmo na primeira vez.",
  "Any letter can be reported to the Sea": "Qualquer carta pode ser relatada ao Mar",
  "Someone looks, within a day": "Alguém analisa, em até um dia",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "Cada relato é lido por uma pessoa em até 24 horas. A carta pode ser retirada do mar e seu autor banido.",
  "Stay a stranger": "Continue um desconhecido",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "Ninguém aqui sabe quem você é, e é melhor assim: não escreva seu sobrenome, seu endereço, seu número nem seus perfis. Uma carta parte e não se chama de volta.",
  "Writing to whoever keeps the lighthouse": "Escrever a quem cuida do farol"
 },
 "ja": {
  "Bottlegram — a slow messaging app": "Bottlegram — ゆっくり届くメッセージ",
  "Skip to content": "本文へ",
  "The waiting": "待つこと",
  "The journal": "日誌",
  "The beaches": "浜辺",
  "The chart": "海図",
  "A slow messaging app": "ゆっくり届くメッセージ",
  "The sea has no use for hurry.": "海に急ぎは要らない。",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "どこかで、見知らぬ誰かがあなたに手紙を書いている。名前もなく、騒がしさもなく。あるのは潮と、それが砂に残していくものだけ。",
  "Coming to the App Store": "App Store にまもなく登場",
  "Not out yet. The sea is still being tested.": "まだ公開前です。海はいま試験中。",
  "The shipwreck": "難破",
  "Sardegna, Italy": "サルデーニャ、イタリア",
  "The point": "要するに",
  "Everything here is slow,": "ここでは何もかもが遅い。",
  "and none of it is by accident.": "そのどれもが、偶然ではない。",
  "You write, and then you wait.": "書いて、それから待つ。",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "手紙は、あいだにある水の分だけ時間がかかる。同じ海の向こう岸なら朝には返事が来るかもしれないし、地球の裏側なら何日も待たされる。早く着かせるために押せるものは何もない。そして最初の一通のあとは、押したいとも思わなくなる。",
  "The beach is empty, and it is yours.": "浜辺には誰もいない。そしてそれはあなたのものだ。",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "誰もオンラインではない。誰も離席していない。誰も入力中ではなく、送信済みも既読もない。あるのは岸と、水の音と、何ひとつ求めてこない水平線だけ。",
  "You have all the time in the world to choose the words.": "言葉を選ぶ時間なら、いくらでもある。",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "手間のかかる手紙のほうが、うまく書ける。ここでは七通を続けざまに送ることもなく、一時間後に言い直すこともなく、送ったものを取り消すこともできない。だからしばらく手元に置いて、早い言葉ではなく本当の言葉を書く。",
  "And the waiting turns out to be the good part.": "そして待つ時間こそが、いちばんいいところだと分かる。",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "日が過ぎる。ほかのことをして暮らす。するとある日、潮が砂に何かを置いていく。誰も予定せず、誰も宣伝せず、誰にも売ることのできなかったもの——見たこともない海岸から届いた、知らない誰かの手書きの文字だ。",
  "Somewhere to go when everything else is shouting.": "ほかのすべてが叫んでいるとき、行ける場所。",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "こちらは朝で、風は陸から吹いてくる。名前は明かさないけれど、家の裏にいちじくを三本植えて、そのうち一本が根づいたことは伝えておく。この瓶がどこかに着いたら、そちらの天気を書いて送ってほしい。",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "毎日、潮が海じゅうの見知らぬ人たちの瓶を運んでくる。やさしい言葉を。言葉は遠くまで行く。",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "海に急ぎは要らない。実在する浜辺にいる見知らぬ誰かへ手紙を書き、潮が何日もかけて運ぶのにまかせる。名前もフィードもない、待つ時間を取り戻したい人のための iPhone アプリ。",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "海に急ぎは要らない。実在する浜辺にいる見知らぬ誰かへ手紙を書き、潮が何日もかけて運ぶのにまかせる。",
  "Sections": "セクション",
  "A nautical chart with the route of a bottle across the open sea": "外洋を渡る瓶の航路を記した海図",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "正午のカーラ・ゴロリッツェのアプリ画面。ターコイズの海、明るい砂、岸に打ち上げられた四本の瓶。",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "日誌のなかの文通。読み手が心のなかで「Black sand」と名づけた相手からの手紙、その下に返信、そして相手の瓶がまだ海の上にあることを告げる一行。",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "海図。カーラ・ゴロリッツェから地中海を出て、大西洋を北上しアイスランドへ向かう航路。瓶はその途中にいる。",
  "Who you are here": "ここでのあなた",
  "No name. No face.": "名前もなく、顔もない。",
  "A seal in wax.": "あるのは蝋の封印だけ。",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "どの漂流者も、いつも同じ紋章を蝋に押す。この海では、それが人のすべてだ。プロフィールも、写真も、履歴もなく、あとから調べられるものは何もない。見知らぬ誰かと、ひとつの岸と、その手書きの文字だけ。",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "読んだことのない言語で書かれてくるかもしれない。ひと押しで自分の言葉になり、もうひと押しで、書かれたとおりの言葉に戻る。",
  "What you keep": "手元に残るもの",
  "A correspondence, not a chat.": "チャットではなく、文通。",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "ここでは手紙が流れて消えたりしない。紙の日誌に、海が届けた順のまま残る。自分のものは片側に、相手のものは反対側に、それぞれの下に岸へ着いた日が書かれている。",
  "You may give a stranger a private name, only for your own pages:": "見知らぬ相手には、自分の日誌のなかだけで通じる名前をつけられる。",
  "the lighthouse keeper": "灯台守",
  "the girl with the boat": "舟をもつ娘",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": "。相手がそれを知ることはない。相手の瓶がまだ海の上にあるときは、日誌がそう告げて、待つように言うだけだ。",
  "The tide keeps its own time — and while you are here, so do you.": "潮には潮の時間がある。そしてここにいるあいだは、あなたにも。",
  "Where you wake up": "目を覚ます場所",
  "A real beach, at the end of the world.": "世界の果てにある、本物の浜辺。",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and the light on them is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "カーラ・ゴロリッツェ。レイニスフィヤラ。アンス・スルス・ダルジャン。実在する海岸を、実在する座標のままに。そこに射す光は、あなたのいまの時刻の光だ。真夜中に開けば浜は暗く、水の上に星が出ている。どれも写真ではない。波の一本一本を、アプリが線で描いている。",
  "The shore": "岸",
  "The hour": "時刻",
  "Take a look around. On arctic beaches, at night, the aurora passes overhead.": "あたりを見てほしい。北極圏の浜では、夜になるとオーロラが頭上を渡っていく。",
  "The crossing": "航路",
  "You can watch it go.": "旅立っていくのを、見ていられる。",
  "your shore": "あなたの岸",
  "still at sea": "まだ海の上",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "投げた瓶は海図に一本の線を残し、その線は眠っているあいだも伸びていく。実線はすでに渡った距離。その先の破線は、向こう岸で誰が待っているかを知ってからでないと現れない。",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "手紙を読んだ相手の島は、そのまま海図に残りつづける。海が引き合わせてくれた人たちだけの、自分だけの地図になる。",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "海図はアプリ自身のものだ。海岸線はパブリックドメインの Natural Earth を内部に持っている。地図サービスを呼ぶことは一度もなく、あなたの居場所に関する情報が手元から出ていくこともない。",
  "Before you go": "行く前に",
  "At the foot of every open letter there is “Report to the Sea”. The correspondence closes, and the letter does not come back to your sand. You can block its author in the same gesture: the tide will never bring you together again, in either direction.": "開いた手紙の末尾には「海に知らせる」がある。文通はそこで閉じ、その手紙が砂に戻ってくることはない。同じ動作で相手をブロックすることもできる。そうすれば潮が二人を引き合わせることは、どちらの向きにも二度とない。",
  "For an urgent report, a problem, or any question at all, this address reaches a real person:": "緊急の報告、不具合、そのほかどんな質問でも、この宛先は実在の人間に届く。",
  "A bottle, thrown well, can reach anyone.": "うまく投げた瓶は、誰のもとにも届きうる。",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "海岸線は Natural Earth（パブリックドメイン）。音は freesound.org（CC0）。地図サービスも、追跡も、Cookie もない。このページはあなたが誰かを知らない——海とまったく同じように。",
  "Map": "地図",
  "Journal": "日誌",
  "Throw": "投げる",
  "Emporium": "商館",
  "Mediterranean": "地中海",
  "Tropical": "熱帯",
  "Arctic": "北極",
  "Volcanic": "火山の島",
  "Wild Atlantic": "荒れた大西洋",
  "Dawn": "夜明け",
  "Day": "昼",
  "Dusk": "夕暮れ",
  "Night": "夜",
  "The storm took the ship, the cargo, and every map you owned.": "嵐が船を、荷を、持っていた海図のすべてを奪った。",
  "The sea, in return, left you one thing: a beach at the end of the world.": "代わりに海が残したものはひとつ — 世界の果ての浜。",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "潮はほかの漂流者の言葉を運ぶという。うまく投げた瓶は、誰にでも届くという。",
  "Your new home": "あなたの新しい住まい",
  "A stranger": "見知らぬ誰か",
  "The rules of the sea": "海の掟",
  "Here you write to strangers, and a stranger deserves the same courtesy as a neighbour. These are the few rules that keep this sea liveable.": "ここでは見知らぬ人に手紙を書きます。見知らぬ人にも、隣人と同じ礼儀を。この海を住める場所に保つ、わずかな掟です。",
  "The sea tolerates none of this": "海はこれらを一切許しません",
  "Harassment, insults, threats, hate or discrimination, sexual content, spam and scams. Zero tolerance: a letter like that is taken out of the sea, and whoever wrote it can be banished from their beach — even the first time.": "嫌がらせ、侮辱、脅迫、憎悪や差別、性的な内容、スパムや詐欺。一切許しません。そうした手紙は海から取り除かれ、書いた人は初回であっても浜辺から追放されることがあります。",
  "Any letter can be reported to the Sea": "どの手紙も海に報告できます",
  "Someone looks, within a day": "1日以内に、誰かが確認します",
  "Every report is read by a person within 24 hours. The letter may be taken out of the sea and its author banished.": "すべての報告は24時間以内に人が読みます。手紙は海から取り除かれ、書いた人が追放されることがあります。",
  "Stay a stranger": "見知らぬ人のままで",
  "Nobody here knows who you are, and that is for the best: do not write your surname, your address, your number or your profiles. A letter sails and cannot be called back.": "ここではあなたが誰かを誰も知りません。それでいいのです。姓、住所、電話番号、アカウントは書かないでください。手紙は一度出たら呼び戻せません。",
  "Writing to whoever keeps the lighthouse": "灯台を守る人へ"
 }
};
const INVARIATE = [",", "Bottlegram", "Cala Goloritzé", "N", "bottlegram@bulbmode.com", "Haukland Beach", "Lofoten, Norway", "Bottles washed ashore: 2", "2", "The beach, as the app draws it — Haukland Beach, Night"];
