/* Le sette lingue del sito.

   GENERATO — non si corregge qui. La sorgente è `genera-lingue.py` (fuori dal
   repo, nella cartella di lavoro), che rimette insieme due cose diverse:

     · le frasi che esistono NELL'APP — le regole del mare, i versi del
       naufragio, il benvenuto — rilette da Localizable.xcstrings a ogni
       rigenerazione. Sono quelle che si dichiarano ad Apple: se divergessero
       dall'app di una virgola sarebbe un difetto, non una sfumatura;
     · le frasi del solo sito, scritte a mano dentro quello script.

   LA CHIAVE È L'INGLESE DELLA PAGINA, non un codice. Così qui si legge
   l'originale accanto alla traduzione, e se un giorno l'inglese in
   `index.html` cambia, la voce smette semplicemente di combaciare e la
   console lo dice — invece di lasciare una traduzione vecchia attaccata a una
   frase nuova, che è il modo in cui questi file mentono.

   L'inglese non sta qui dentro: sta nell'HTML, ed è quello che legge chi
   arriva senza JavaScript. */
const LINGUE = {
 "it": {
  "Bottlegram — a slow messaging app": "Bottlegram — un'app di messaggi lenti",
  "Skip to content": "Vai al contenuto",
  "How it works": "Come funziona",
  "Three bottles a day,": "Tre bottiglie al giorno,",
  "and a whole sea in between.": "e un mare intero in mezzo.",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram è una applicazione di messaggistica lenta. Non scrivi a nessuno in particolare, è la corrente a decidere il tuo interlocutore.",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "Un tratto di mare visto dall'alto: due coste, e una bottiglia che va dall'una all'altra.",
  "Your shore": "La tua riva",
  "Someone's shore": "La riva di qualcuno",
  "six to twenty-four hours": "da sei a ventiquattro ore",
  "You throw a bottle": "Lanci una bottiglia",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "Ogni giorno il mare ti lascia tre bottiglie. Ci metti dentro un messaggio e lo affidi alla corrente, senza scegliere per chi.",
  "Someone finds it": "Qualcuno la trova",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "Qualche ora dopo approda sulla spiaggia di un altro naufrago. Allo stesso modo, sulla tua sabbia arrivano le bottiglie degli altri.",
  "And answers, if they want to": "E se vuole, risponde",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "Chi trova la tua lettera può risponderti, e da lì nasce una corrispondenza. Nessuno è obbligato: una bottiglia senza risposta è una cosa che in mare succede.",
  "The chart follows them": "La carta le segue",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "Sulla mappa guardi le bottiglie che hai lanciato, e quelle che tornano verso di te dalle rive che conosci già.",
  "The waiting": "L'attesa",
  "The journal": "Il diario",
  "The beaches": "Le spiagge",
  "The chart": "La carta",
  "A slow messaging app": "Un'app di messaggi lenti",
  "The sea has no use for hurry.": "Il mare non sa che farsene della fretta.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Da qualche parte, uno sconosciuto ti sta scrivendo. Nessun nome. Nessun rumore. Solo la marea, e quello che decide di lasciarti sulla sabbia.",
  "Coming to the App Store": "Presto sull'App Store",
  "Not out yet. The sea is still being tested.": "Non è ancora uscita. Il mare è ancora in collaudo.",
  "The shipwreck": "Il naufragio",
  "Sardegna, Italy": "Sardegna, Italia",
  "The point": "Il punto",
  "Everything here is slow,": "Qui è tutto lento,",
  "and none of it is by accident.": "e non è successo per caso.",
  "You write, and then you wait.": "Scrivi, e poi aspetti.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Una lettera ci mette quanto ci mette l'acqua che vi separa. Una riva sullo stesso mare può risponderti entro domattina; dall'altra parte del mondo ti farà aspettare giorni. Non c'è niente da toccare che la faccia arrivare prima — e dopo la prima volta smetti di volerlo.",
  "The beach is empty, and it is yours.": "La spiaggia è vuota, ed è tua.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Nessuno è online. Nessuno è assente. Nessuno sta scrivendo, e niente è segnato come consegnato, visualizzato o letto. C'è una riva, il rumore dell'acqua, e un orizzonte che non ti chiede niente.",
  "You have all the time in the world to choose the words.": "Hai tutto il tempo del mondo per scegliere le parole.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Una lettera che costa qualcosa si scrive meglio. Qui non ne spari sette di fila, non ti correggi un'ora dopo, e non puoi richiamarne indietro nessuna. Così ci stai sopra un po', e dici la cosa vera invece di quella veloce.",
  "And the waiting turns out to be the good part.": "E l'attesa si scopre essere la parte bella.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Passano i giorni. Fai altro. Poi la marea ti lascia sulla sabbia una cosa che nessuno aveva programmato, nessuno aveva sponsorizzato e nessuno avrebbe potuto venderti — la calligrafia di uno sconosciuto, da una costa che non hai mai visto.",
  "Somewhere to savour the quiet, while everything else is racing.": "Un posto dove godersi la quiete, mentre tutto il resto corre.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Qui è mattina e il vento viene da terra. Non ti dirò il mio nome, ma ti dirò che ho piantato tre fichi dietro casa e uno ha attecchito. Se questa bottiglia approda da qualche parte, scrivimi e dimmi che tempo fa da te.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Ogni giorno la marea porterà bottiglie di sconosciuti da tutto il mare. Parla con gentilezza — le parole vanno lontano.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Il mare non sa che farsene della fretta. Scrivi a uno sconosciuto su una spiaggia vera e lascia che la marea ci metta giorni a portarla — niente nomi, niente feed, un'app per iPhone per chi si rivuole indietro l'attesa.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Il mare non sa che farsene della fretta. Scrivi a uno sconosciuto su una spiaggia vera e lascia che la marea ci metta giorni a portarla.",
  "Sections": "Sezioni",
  "A nautical chart with the route of a bottle across the open sea": "Una carta nautica con la rotta di una bottiglia attraverso il mare aperto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "L'app a Cala Goloritzé a mezzogiorno: mare turchese, sabbia chiara e quattro bottiglie approdate sulla riva.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Un carteggio nel diario: la lettera di uno sconosciuto a cui chi legge ha dato in privato il nome «Black sand», sotto la risposta, e un avviso che dice che una loro bottiglia è ancora in mare.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carta nautica: una rotta disegnata da Cala Goloritzé fuori dal Mediterraneo e su per l'Atlantico verso l'Islanda, con la bottiglia a metà strada.",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "L'alba ad Anse Source d'Argent come la disegna l'app: un cielo rosa, l'acqua calma, una palma sulla sabbia.",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "Mezzogiorno a Cala Goloritzé come lo disegna l'app: cielo azzurro, mare turchese, bottiglie sulla sabbia chiara.",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "Il tramonto a Reynisfjara come lo disegna l'app: un cielo di brace sopra la sabbia vulcanica nera.",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "La notte a Haukland Beach come la disegna l'app: l'aurora sopra un mare artico scuro.",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "Gira da sola: l'alba a La Digue, mezzogiorno in Sardegna, il tramonto sulla sabbia nera di Reynisfjara, e una notte artica con l'aurora sopra la testa. Nell'app te ne tocca una, e non la scegli tu — che è la cosa più bella.",
  "One of the 250 shores the storm knows. Yours could be any of them.": "Una delle 250 rive che la tempesta conosce. La tua potrebbe essere una qualsiasi.",
  "Vík, Iceland": "Vík, Islanda",
  "La Digue, Seychelles": "La Digue, Seychelles",
  "Lofoten, Norway": "Lofoten, Norvegia",
  "Sintra, Portugal": "Sintra, Portogallo",
  "One last thing": "Un'ultima cosa",
  "The tide is already on its way.": "La marea è già in viaggio.",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "Su una riva che non hai mai visto, uno sconosciuto sta spingendo il tappo in una bottiglia proprio adesso. Il mare deciderà su quale sabbia farla approdare. Magari proprio sulla tua.",
  "Who you are here": "Chi sei, qui",
  "No name. No face.": "Nessun nome. Nessun volto.",
  "A seal in wax.": "Un sigillo di ceralacca.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Ogni naufrago imprime sempre lo stesso emblema nella cera — e su questo mare quello è tutto di una persona: nessun profilo, nessuna fotografia, nessuno storico, niente da andare a cercare dopo. Uno sconosciuto, una riva, e la sua calligrafia.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Può darsi che ti scrivano in una lingua che non hai mai letto. Un tocco la porta nella tua; un altro rimette le loro parole com'erano, esattamente come le hanno scritte.",
  "What you keep": "Quello che conservi",
  "A correspondence, not a chat.": "Un carteggio, non una chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Qui le lettere non scorrono via. Restano in un diario di carta, nell'ordine in cui il mare le ha consegnate — le tue da una parte, le loro dall'altra, ognuna con sotto il giorno in cui è approdata.",
  "You may give a stranger a private name, only for your own pages:": "A uno sconosciuto puoi dare un nome privato, solo per le tue pagine:",
  "the lighthouse keeper": "il guardiano del faro",
  "the girl with the boat": "la ragazza con la barca",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Loro non lo sapranno mai. E quando una loro bottiglia è ancora in mare, il diario lo dice e basta, e ti chiede di aspettare.",
  "The tide keeps its own time — and while you are here, so do you.": "La marea ha un suo tempo — e finché sei qui, ce l'hai anche tu.",
  "Where you wake up": "Dove ti svegli",
  "A real beach, and not one you picked.": "Una spiaggia vera, e non l'hai scelta tu.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Tratti di costa veri alle loro coordinate vere — e la tua te la dà la sorte. Decide la tempesta dove lasciarti, e da quella mattina è casa. La luce che ci sta sopra è quella della tua ora: aprila a mezzanotte e la tua spiaggia è buia, con le stelle sull'acqua. Nessuna di queste è una fotografia. Ogni onda la disegna l'app, linea per linea.",
  "The crossing": "La traversata",
  "You can watch it go.": "Puoi guardarla andare.",
  "your shore": "la tua riva",
  "still at sea": "ancora in mare",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Una bottiglia che hai lanciato lascia una linea sulla carta, e la linea cresce mentre dormi. Il tratto pieno è la distanza già navigata; il tratteggio davanti compare solo quando sai chi aspetta dall'altra parte.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Le isole degli sconosciuti di cui hai letto le lettere restano segnate per sempre — una mappa privata di tutti quelli che il mare ti ha presentato.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carta è tutta dell'app: coste da Natural Earth, di pubblico dominio, portate dentro. Nessun servizio di mappe viene mai chiamato, e niente di dove sei esce dalle tue mani.",
  "·": "·",
  "Privacy": "Privacy",
  "Support": "Supporto",
  "A bottle, thrown well, can reach anyone.": "Una bottiglia, lanciata bene, può raggiungere chiunque.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Coste da Natural Earth (pubblico dominio). Suoni da freesound.org (CC0). Nessun servizio di mappe, nessun tracciamento, nessun cookie: questa pagina non sa chi sei, esattamente come il mare.",
  "The storm took the ship, the cargo, and every map you owned.": "La tempesta si è presa la nave, il carico e ogni mappa che possedevi.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "Il mare, in cambio, ti ha lasciato una cosa sola: una spiaggia in capo al mondo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dicono che la marea porti parole di altri naufraghi. E che una bottiglia, lanciata bene, possa raggiungere chiunque.",
  "Your new home": "La tua nuova casa",
  "A stranger": "Uno sconosciuto"
 },
 "es": {
  "Bottlegram — a slow messaging app": "Bottlegram — una app de mensajes lentos",
  "Skip to content": "Ir al contenido",
  "How it works": "Cómo funciona",
  "Three bottles a day,": "Tres botellas al día,",
  "and a whole sea in between.": "y un mar entero en medio.",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram es una aplicación de mensajería lenta. No escribes a nadie en particular: es la corriente la que decide con quién acabas hablando.",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "Un trecho de mar visto desde arriba: dos costas, y una botella que va de una a otra.",
  "Your shore": "Tu orilla",
  "Someone's shore": "La orilla de alguien",
  "six to twenty-four hours": "de seis a veinticuatro horas",
  "You throw a bottle": "Lanzas una botella",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "Cada día el mar te deja tres botellas. Metes dentro un mensaje y lo confías a la corriente, sin elegir para quién.",
  "Someone finds it": "Alguien la encuentra",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "Unas horas después llega a la playa de otro náufrago. Del mismo modo, a tu arena llegan las botellas de los demás.",
  "And answers, if they want to": "Y si quiere, responde",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "Quien encuentre tu carta puede contestarte, y de ahí nace una correspondencia. Nadie está obligado: una botella sin respuesta es algo que en el mar pasa.",
  "The chart follows them": "La carta las sigue",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "En el mapa miras las botellas que has lanzado, y las que vuelven hacia ti desde las orillas que ya conoces.",
  "The waiting": "La espera",
  "The journal": "El diario",
  "The beaches": "Las playas",
  "The chart": "La carta náutica",
  "A slow messaging app": "Una app de mensajes lentos",
  "The sea has no use for hurry.": "Al mar no le sirve de nada la prisa.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "En algún lugar, un desconocido te está escribiendo. Sin nombres. Sin ruido. Solo la marea, y lo que decida dejarte en la arena.",
  "Coming to the App Store": "Pronto en la App Store",
  "Not out yet. The sea is still being tested.": "Todavía no ha salido. El mar aún se está probando.",
  "The shipwreck": "El naufragio",
  "Sardegna, Italy": "Cerdeña, Italia",
  "The point": "El porqué",
  "Everything here is slow,": "Aquí todo es lento,",
  "and none of it is by accident.": "y nada de ello es casualidad.",
  "You write, and then you wait.": "Escribes, y luego esperas.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Una carta tarda lo que tarde el agua que os separa. Una orilla del mismo mar puede responder por la mañana; el otro extremo del mundo te hará esperar días. No hay nada que puedas tocar para que llegue antes, y después de la primera dejas de quererlo.",
  "The beach is empty, and it is yours.": "La playa está vacía, y es tuya.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Nadie está en línea. Nadie está ausente. Nadie está escribiendo, y nada aparece como entregado, visto o leído. Hay una orilla, el sonido del agua y un horizonte que no te pide nada.",
  "You have all the time in the world to choose the words.": "Tienes todo el tiempo del mundo para elegir las palabras.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Una carta que cuesta algo se escribe mejor. Aquí no soltarás siete seguidas, no te corregirás una hora después y no puedes retirar ninguna. Así que te quedas un rato con ella, y dices lo verdadero en lugar de lo rápido.",
  "And the waiting turns out to be the good part.": "Y resulta que la espera es lo mejor.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Pasan los días. Haces otras cosas. Entonces la marea deja en tu arena algo que nadie programó, nadie promocionó y nadie podría haberte vendido: la letra de un desconocido, desde una costa que nunca has visto.",
  "Somewhere to savour the quiet, while everything else is racing.": "Un lugar donde disfrutar de la calma, mientras todo lo demás corre.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Aquí es de mañana y el viento viene de tierra. No te diré mi nombre, pero sí que planté tres higueras detrás de la casa y una prendió. Si esta botella llega a alguna parte, escríbeme y dime qué tiempo hace donde estás.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Cada día la marea traerá botellas de desconocidos de todo el mar. Habla con amabilidad: las palabras llegan lejos.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Al mar no le sirve de nada la prisa. Escribe a un desconocido en una playa de verdad y deja que la marea tarde días en llevarla: sin nombres, sin feeds, una app de iPhone para quien quiere recuperar la espera.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Al mar no le sirve de nada la prisa. Escribe a un desconocido en una playa de verdad y deja que la marea tarde días en llevarla.",
  "Sections": "Secciones",
  "A nautical chart with the route of a bottle across the open sea": "Una carta náutica con la ruta de una botella a través del mar abierto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "La app en Cala Goloritzé a mediodía: mar turquesa, arena clara y cuatro botellas llegadas a la orilla.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Una correspondencia en el diario: la carta de un desconocido a quien quien lee ha llamado en privado «Black sand», debajo la respuesta, y un aviso de que una botella suya sigue en el mar.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carta náutica: una ruta trazada desde Cala Goloritzé fuera del Mediterráneo y hacia el norte por el Atlántico rumbo a Islandia, con la botella a medio camino.",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "El alba en Anse Source d'Argent tal como la dibuja la app: un cielo rosado, agua en calma, una palmera en la arena.",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "El mediodía en Cala Goloritzé tal como lo dibuja la app: cielo azul, mar turquesa, botellas en la arena clara.",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "El atardecer en Reynisfjara tal como lo dibuja la app: un cielo de brasas sobre la arena volcánica negra.",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "La noche en Haukland Beach tal como la dibuja la app: la aurora sobre un mar ártico oscuro.",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "Gira sola: el alba en La Digue, el mediodía en Cerdeña, el atardecer en la arena negra de Reynisfjara y una noche ártica con la aurora por encima. En la app te toca una, y no la eliges tú — que es lo mejor de todo.",
  "One of the 250 shores the storm knows. Yours could be any of them.": "Una de las 250 orillas que la tormenta conoce. La tuya podría ser cualquiera.",
  "Vík, Iceland": "Vík, Islandia",
  "La Digue, Seychelles": "La Digue, Seychelles",
  "Lofoten, Norway": "Lofoten, Noruega",
  "Sintra, Portugal": "Sintra, Portugal",
  "One last thing": "Una última cosa",
  "The tide is already on its way.": "La marea ya está en camino.",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "En una orilla que nunca has visto, un desconocido está apretando el corcho de una botella ahora mismo. El mar decidirá qué arena toca después. Quizá justo la tuya.",
  "Who you are here": "Quién eres aquí",
  "No name. No face.": "Sin nombre. Sin rostro.",
  "A seal in wax.": "Un sello de lacre.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Cada náufrago imprime siempre el mismo emblema en el lacre, y en este mar eso es toda una persona: sin perfil, sin fotografía, sin historial, sin nada que buscar después. Un desconocido, una orilla y su letra.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Puede que te escriban en una lengua que nunca has leído. Un toque la convierte en la tuya; otro devuelve sus palabras tal como las escribieron.",
  "What you keep": "Lo que conservas",
  "A correspondence, not a chat.": "Una correspondencia, no un chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Aquí las cartas no se van con el desplazamiento. Se quedan en un diario de papel, en el orden en que el mar las entregó: las tuyas de un lado, las suyas del otro, cada una con el día en que llegó a la orilla escrito debajo.",
  "You may give a stranger a private name, only for your own pages:": "A un desconocido puedes darle un nombre privado, solo para tus páginas:",
  "the lighthouse keeper": "el farero",
  "the girl with the boat": "la chica de la barca",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Ellos nunca lo sabrán. Y cuando una botella suya sigue en el agua, el diario lo dice sin más, y te pide que esperes.",
  "The tide keeps its own time — and while you are here, so do you.": "La marea lleva su propio tiempo, y mientras estés aquí, tú también.",
  "Where you wake up": "Dónde te despiertas",
  "A real beach, and not one you picked.": "Una playa de verdad, y no la has elegido tú.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Tramos de costa reales en sus coordenadas reales, y la tuya te toca en suerte. La tormenta decide dónde dejarte, y desde esa mañana es tu casa. La luz que la baña es la de tu propia hora: ábrela a medianoche y tu playa está a oscuras, con las estrellas sobre el agua. Ninguna de estas es una fotografía. Cada ola la dibuja la app, línea a línea.",
  "The crossing": "La travesía",
  "You can watch it go.": "Puedes verla marchar.",
  "your shore": "tu orilla",
  "still at sea": "aún en el mar",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Una botella que has lanzado deja una línea en la carta, y la línea crece mientras duermes. El trazo continuo es la distancia ya navegada; los guiones de delante solo aparecen cuando sabes quién espera al otro extremo.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Las islas de los desconocidos cuyas cartas has leído quedan marcadas para siempre: un mapa privado de todos los que el mar te ha presentado.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carta es de la propia app: costas de Natural Earth, de dominio público, llevadas dentro. Nunca se llama a ningún servicio de mapas, y nada sobre dónde estás sale de tus manos.",
  "·": "·",
  "Privacy": "Privacidad",
  "Support": "Soporte",
  "A bottle, thrown well, can reach anyone.": "Una botella, bien lanzada, puede llegar a cualquiera.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Costas de Natural Earth (dominio público). Sonidos de freesound.org (CC0). Sin servicio de mapas, sin rastreo, sin cookies: esta página no sabe quién eres, igual que el mar.",
  "The storm took the ship, the cargo, and every map you owned.": "La tormenta se llevó el barco, la carga y todos los mapas que tenías.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "El mar, a cambio, te dejó una sola cosa: una playa en el fin del mundo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dicen que la marea trae palabras de otros náufragos. Y que una botella, bien lanzada, puede llegar a cualquiera.",
  "Your new home": "Tu nuevo hogar",
  "A stranger": "Un desconocido"
 },
 "fr": {
  "Bottlegram — a slow messaging app": "Bottlegram — une messagerie lente",
  "Skip to content": "Aller au contenu",
  "How it works": "Comment ça marche",
  "Three bottles a day,": "Trois bouteilles par jour,",
  "and a whole sea in between.": "et une mer entière entre les deux.",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram est une application de messagerie lente. Tu n'écris à personne en particulier — c'est le courant qui décide de ton interlocuteur.",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "Une étendue de mer vue d'en haut : deux côtes, et une bouteille qui va de l'une à l'autre.",
  "Your shore": "Ta rive",
  "Someone's shore": "La rive de quelqu'un",
  "six to twenty-four hours": "de six à vingt-quatre heures",
  "You throw a bottle": "Tu lances une bouteille",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "Chaque jour la mer te laisse trois bouteilles. Tu y glisses un message et tu le confies au courant, sans choisir pour qui.",
  "Someone finds it": "Quelqu'un la trouve",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "Quelques heures plus tard, elle échoue sur la plage d'un autre naufragé. De la même façon, les bouteilles des autres échouent sur ton sable.",
  "And answers, if they want to": "Et s'il veut, il répond",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "Celui qui trouve ta lettre peut te répondre, et une correspondance commence. Personne n'y est tenu : une bouteille sans réponse, ça arrive en mer.",
  "The chart follows them": "La carte les suit",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "Sur la carte, tu regardes les bouteilles que tu as lancées, et celles qui reviennent vers toi des rives que tu connais déjà.",
  "The waiting": "L'attente",
  "The journal": "Le journal",
  "The beaches": "Les plages",
  "The chart": "La carte",
  "A slow messaging app": "Une messagerie lente",
  "The sea has no use for hurry.": "La mer n'a que faire de la hâte.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Quelque part, un inconnu vous écrit. Aucun nom. Aucun bruit. Rien que la marée, et ce qu'elle décide de laisser sur votre sable.",
  "Coming to the App Store": "Bientôt sur l'App Store",
  "Not out yet. The sea is still being tested.": "Pas encore sortie. La mer est encore à l'essai.",
  "The shipwreck": "Le naufrage",
  "Sardegna, Italy": "Sardaigne, Italie",
  "The point": "L'essentiel",
  "Everything here is slow,": "Ici tout est lent,",
  "and none of it is by accident.": "et rien de tout cela n'est un hasard.",
  "You write, and then you wait.": "Vous écrivez, puis vous attendez.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Une lettre met le temps que met l'eau qui vous sépare. Un rivage sur la même mer répondra peut-être au matin ; l'autre bout du monde vous fera attendre des jours. Rien de ce que vous toucherez ne la fera venir plus tôt — et après la première, vous cessez de le souhaiter.",
  "The beach is empty, and it is yours.": "La plage est vide, et elle est à vous.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Personne n'est en ligne. Personne n'est absent. Personne n'est en train d'écrire, et rien n'est marqué distribué, vu ou lu. Il y a un rivage, le bruit de l'eau, et un horizon qui ne vous demande rien.",
  "You have all the time in the world to choose the words.": "Vous avez tout le temps du monde pour choisir les mots.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Une lettre qui coûte quelque chose s'écrit mieux. Ici vous n'en enverrez pas sept d'affilée, vous ne vous corrigerez pas une heure plus tard, et vous ne pouvez en rappeler aucune. Alors vous restez un moment avec elle, et vous dites la chose vraie plutôt que la chose rapide.",
  "And the waiting turns out to be the good part.": "Et l'attente se révèle être le meilleur.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Les jours passent. Vous faites autre chose. Puis la marée laisse sur votre sable quelque chose que personne n'avait programmé, que personne n'avait promu et que personne n'aurait pu vous vendre — l'écriture d'un inconnu, venue d'une côte que vous n'avez jamais vue.",
  "Somewhere to savour the quiet, while everything else is racing.": "Un endroit où savourer le calme, pendant que tout le reste court.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Ici c'est le matin et le vent vient de la terre. Je ne vous dirai pas mon nom, mais je vous dirai que j'ai planté trois figuiers derrière la maison et que l'un d'eux a pris. Si cette bouteille aborde quelque part, écrivez-moi le temps qu'il fait chez vous.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Chaque jour, la marée apportera des bouteilles d'inconnus de toute la mer. Parlez avec douceur — les mots vont loin.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "La mer n'a que faire de la hâte. Écrivez à un inconnu sur une vraie plage et laissez la marée mettre des jours à l'emporter — aucun nom, aucun fil, une application iPhone pour qui veut retrouver l'attente.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "La mer n'a que faire de la hâte. Écrivez à un inconnu sur une vraie plage et laissez la marée mettre des jours à l'emporter.",
  "Sections": "Sections",
  "A nautical chart with the route of a bottle across the open sea": "Une carte marine avec la route d'une bouteille en pleine mer",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "L'application à Cala Goloritzé à midi : mer turquoise, sable clair et quatre bouteilles échouées sur le rivage.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Une correspondance dans le journal : la lettre d'un inconnu que le lecteur a nommé en privé « Black sand », la réponse en dessous, et une note indiquant qu'une de leurs bouteilles est encore en mer.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "La carte marine : une route tracée depuis Cala Goloritzé, hors de la Méditerranée et vers le nord à travers l'Atlantique en direction de l'Islande, la bouteille à mi-parcours.",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "L'aube à Anse Source d'Argent telle que l'application la dessine : un ciel rose, une eau calme, un palmier sur le sable.",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "Midi à Cala Goloritzé tel que l'application le dessine : ciel bleu, mer turquoise, des bouteilles sur le sable clair.",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "Le crépuscule à Reynisfjara tel que l'application le dessine : un ciel de braise sur le sable volcanique noir.",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "La nuit à Haukland Beach telle que l'application la dessine : l'aurore au-dessus d'une mer arctique sombre.",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "Elle tourne toute seule : l'aube à La Digue, midi en Sardaigne, le crépuscule sur le sable noir de Reynisfjara, et une nuit arctique avec l'aurore au-dessus. Dans l'application vous en recevez une, et vous ne la choisissez pas — c'est ce qu'il y a de plus beau.",
  "One of the 250 shores the storm knows. Yours could be any of them.": "Un des 250 rivages que la tempête connaît. Le vôtre pourrait être n'importe lequel.",
  "Vík, Iceland": "Vík, Islande",
  "La Digue, Seychelles": "La Digue, Seychelles",
  "Lofoten, Norway": "Lofoten, Norvège",
  "Sintra, Portugal": "Sintra, Portugal",
  "One last thing": "Une dernière chose",
  "The tide is already on its way.": "La marée est déjà en route.",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "Sur un rivage que vous n'avez jamais vu, un inconnu enfonce le bouchon d'une bouteille en ce moment même. La mer décidera quel sable elle touchera ensuite. Peut-être le vôtre.",
  "Who you are here": "Qui vous êtes ici",
  "No name. No face.": "Pas de nom. Pas de visage.",
  "A seal in wax.": "Un sceau de cire.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Chaque naufragé imprime toujours le même emblème dans la cire — et sur cette mer, c'est là tout un être : pas de profil, pas de photographie, pas d'historique, rien à aller chercher ensuite. Un inconnu, un rivage, et son écriture.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Ils vous écrivent peut-être dans une langue que vous n'avez jamais lue. Une touche la met dans la vôtre ; une autre remet leurs mots exactement comme ils les ont écrits.",
  "What you keep": "Ce que vous gardez",
  "A correspondence, not a chat.": "Une correspondance, pas une conversation.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Ici, les lettres ne défilent pas au loin. Elles restent dans un journal de papier, dans l'ordre où la mer les a remises — les vôtres d'un côté, les leurs de l'autre, chacune avec, en dessous, le jour où elle a abordé.",
  "You may give a stranger a private name, only for your own pages:": "Vous pouvez donner à un inconnu un nom privé, rien que pour vos pages :",
  "the lighthouse keeper": "le gardien du phare",
  "the girl with the boat": "la fille au bateau",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Ils ne le sauront jamais. Et lorsqu'une de leurs bouteilles est encore sur l'eau, le journal le dit simplement, et vous demande d'attendre.",
  "The tide keeps its own time — and while you are here, so do you.": "La marée a son propre temps — et tant que vous êtes ici, vous aussi.",
  "Where you wake up": "Où vous vous réveillez",
  "A real beach, and not one you picked.": "Une vraie plage, et ce n'est pas vous qui l'avez choisie.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. De vraies portions de côte à leurs vraies coordonnées — et la vôtre vous échoit au hasard. C'est la tempête qui décide où elle vous laisse, et dès ce matin-là c'est chez vous. La lumière qui la baigne est celle de votre propre heure : ouvrez à minuit et votre plage est sombre, les étoiles au-dessus de l'eau. Aucune n'est une photographie. Chaque vague est dessinée par l'application, trait par trait.",
  "The crossing": "La traversée",
  "You can watch it go.": "Vous pouvez la regarder s'en aller.",
  "your shore": "votre rivage",
  "still at sea": "encore en mer",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Une bouteille que vous avez lancée laisse une ligne sur la carte, et la ligne grandit pendant votre sommeil. Le trait plein est la distance déjà parcourue ; les pointillés devant n'apparaissent qu'une fois que vous savez qui attend à l'autre bout.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Les îles des inconnus dont vous avez lu les lettres restent marquées pour de bon — une carte privée de tous ceux que la mer vous a présentés.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "La carte appartient à l'application : côtes issues de Natural Earth, domaine public, embarquées avec elle. Aucun service cartographique n'est jamais appelé, et rien de votre position ne quitte vos mains.",
  "·": "·",
  "Privacy": "Confidentialité",
  "Support": "Assistance",
  "A bottle, thrown well, can reach anyone.": "Une bouteille, bien lancée, peut atteindre n'importe qui.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Côtes issues de Natural Earth (domaine public). Sons de freesound.org (CC0). Aucun service cartographique, aucun traçage, aucun cookie : cette page ne sait pas qui vous êtes, exactement comme la mer.",
  "The storm took the ship, the cargo, and every map you owned.": "La tempête a pris le navire, la cargaison et toutes les cartes que tu possédais.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "La mer, en échange, ne t'a laissé qu'une chose : une plage au bout du monde.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "On dit que la marée porte les mots d'autres naufragés. Et qu'une bouteille, bien lancée, peut atteindre n'importe qui.",
  "Your new home": "Ton nouveau chez-toi",
  "A stranger": "Un inconnu"
 },
 "de": {
  "Bottlegram — a slow messaging app": "Bottlegram — langsame Nachrichten",
  "Skip to content": "Zum Inhalt springen",
  "How it works": "Wie es funktioniert",
  "Three bottles a day,": "Drei Flaschen am Tag,",
  "and a whole sea in between.": "und dazwischen ein ganzes Meer.",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram ist eine App für langsame Nachrichten. Du schreibst niemandem bestimmten — die Strömung entscheidet, mit wem du am Ende sprichst.",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "Ein Stück Meer von oben: zwei Küsten und eine Flasche, die von der einen zur anderen treibt.",
  "Your shore": "Dein Ufer",
  "Someone's shore": "Jemandes Ufer",
  "six to twenty-four hours": "sechs bis vierundzwanzig Stunden",
  "You throw a bottle": "Du wirfst eine Flasche",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "Jeden Tag lässt dir das Meer drei Flaschen da. Du legst eine Nachricht hinein und übergibst sie der Strömung, ohne zu wählen, für wen.",
  "Someone finds it": "Jemand findet sie",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "Stunden später strandet sie am Strand eines anderen Schiffbrüchigen. Genauso stranden fremde Flaschen an deinem Sand.",
  "And answers, if they want to": "Und antwortet, wenn er mag",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "Wer deinen Brief findet, kann antworten, und daraus wird ein Briefwechsel. Niemand muss: eine Flasche ohne Antwort kommt auf See vor.",
  "The chart follows them": "Die Karte folgt ihnen",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "Auf der Karte siehst du deine geworfenen Flaschen und die, die von den Ufern, die du schon kennst, zu dir zurückkommen.",
  "The waiting": "Das Warten",
  "The journal": "Das Tagebuch",
  "The beaches": "Die Strände",
  "The chart": "Die Seekarte",
  "A slow messaging app": "Langsame Nachrichten",
  "The sea has no use for hurry.": "Das Meer weiß mit Eile nichts anzufangen.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Irgendwo da draußen schreibt Ihnen ein Fremder. Keine Namen. Kein Lärm. Nur die Gezeiten und das, was sie in Ihrem Sand zurücklassen.",
  "Coming to the App Store": "Bald im App Store",
  "Not out yet. The sea is still being tested.": "Noch nicht erschienen. Das Meer wird noch erprobt.",
  "The shipwreck": "Der Schiffbruch",
  "Sardegna, Italy": "Sardinien, Italien",
  "The point": "Worum es geht",
  "Everything here is slow,": "Hier ist alles langsam,",
  "and none of it is by accident.": "und nichts davon ist ein Versehen.",
  "You write, and then you wait.": "Sie schreiben, und dann warten Sie.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Ein Brief braucht so lange, wie das Wasser zwischen Ihnen braucht. Eine Küste am selben Meer antwortet vielleicht bis zum Morgen; die andere Seite der Welt lässt Sie Tage warten. Kein Tippen bringt ihn früher — und nach dem ersten Mal wollen Sie es gar nicht mehr.",
  "The beach is empty, and it is yours.": "Der Strand ist leer, und er gehört Ihnen.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Niemand ist online. Niemand ist abwesend. Niemand tippt, und nichts ist als zugestellt, gesehen oder gelesen markiert. Es gibt ein Ufer, das Geräusch des Wassers und einen Horizont, der nichts von Ihnen will.",
  "You have all the time in the world to choose the words.": "Sie haben alle Zeit der Welt, die Worte zu wählen.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Ein Brief, der etwas kostet, wird besser geschrieben. Hier feuern Sie nicht sieben hintereinander ab, korrigieren sich nicht eine Stunde später und können keinen zurückholen. Also bleiben Sie eine Weile dabei und sagen das Wahre statt des Schnellen.",
  "And the waiting turns out to be the good part.": "Und das Warten stellt sich als das Schönste heraus.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Tage vergehen. Sie tun anderes. Dann lässt die Flut etwas in Ihrem Sand zurück, das niemand geplant, niemand beworben und niemand Ihnen hätte verkaufen können — die Handschrift eines Fremden, von einer Küste, die Sie nie gesehen haben.",
  "Somewhere to savour the quiet, while everything else is racing.": "Ein Ort, an dem man die Stille genießt, während alles andere rennt.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Hier ist Morgen und der Wind kommt vom Land. Ich nenne Ihnen meinen Namen nicht, aber ich sage Ihnen, dass ich hinter dem Haus drei Feigenbäume gepflanzt habe und einer angewachsen ist. Wenn diese Flasche irgendwo anlandet, schreiben Sie mir, wie das Wetter bei Ihnen ist.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Jeden Tag bringt die Flut Flaschen von Fremden aus dem ganzen Meer. Sprechen Sie freundlich — Worte reisen weit.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "Das Meer weiß mit Eile nichts anzufangen. Schreiben Sie einem Fremden an einem wirklichen Strand und lassen Sie die Flut Tage dafür brauchen — keine Namen, keine Feeds, eine iPhone-App für alle, die das Warten zurückwollen.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "Das Meer weiß mit Eile nichts anzufangen. Schreiben Sie einem Fremden an einem wirklichen Strand und lassen Sie die Flut Tage dafür brauchen.",
  "Sections": "Abschnitte",
  "A nautical chart with the route of a bottle across the open sea": "Eine Seekarte mit der Route einer Flasche über das offene Meer",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "Die App an der Cala Goloritzé zur Mittagszeit: türkisfarbenes Meer, heller Sand und vier angespülte Flaschen.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Ein Briefwechsel im Tagebuch: der Brief eines Fremden, den die lesende Person im Stillen „Black sand“ genannt hat, darunter die Antwort und ein Hinweis, dass eine Flasche von ihnen noch auf See ist.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "Die Seekarte: eine Route von der Cala Goloritzé aus dem Mittelmeer hinaus und nordwärts über den Atlantik Richtung Island, die Flasche auf halbem Weg.",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "Morgengrauen an der Anse Source d'Argent, wie die App es zeichnet: ein rosa Himmel, stilles Wasser, eine Palme im Sand.",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "Mittag an der Cala Goloritzé, wie die App ihn zeichnet: blauer Himmel, türkisfarbenes Meer, Flaschen im hellen Sand.",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "Dämmerung in Reynisfjara, wie die App sie zeichnet: ein glutroter Himmel über schwarzem Vulkansand.",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "Nacht am Haukland Beach, wie die App sie zeichnet: das Polarlicht über einem dunklen arktischen Meer.",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "Er wechselt von selbst: Morgengrauen auf La Digue, Mittag auf Sardinien, Dämmerung auf dem schwarzen Sand von Reynisfjara und eine arktische Nacht mit dem Polarlicht darüber. In der App bekommen Sie einen Strand, und Sie suchen ihn nicht aus — das ist das Schönste daran.",
  "One of the 250 shores the storm knows. Yours could be any of them.": "Eines von 250 Ufern, die der Sturm kennt. Ihres könnte jedes davon sein.",
  "Vík, Iceland": "Vík, Island",
  "La Digue, Seychelles": "La Digue, Seychellen",
  "Lofoten, Norway": "Lofoten, Norwegen",
  "Sintra, Portugal": "Sintra, Portugal",
  "One last thing": "Eine letzte Sache",
  "The tide is already on its way.": "Die Flut ist schon unterwegs.",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "An einem Ufer, das Sie nie gesehen haben, drückt gerade ein Fremder den Korken in eine Flasche. Das Meer entscheidet, wessen Sand sie als Nächstes berührt. Vielleicht Ihren.",
  "Who you are here": "Wer Sie hier sind",
  "No name. No face.": "Kein Name. Kein Gesicht.",
  "A seal in wax.": "Ein Siegel in Wachs.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Jeder Schiffbrüchige drückt stets dasselbe Emblem ins Wachs — und auf diesem Meer ist das ein ganzer Mensch: kein Profil, kein Foto, keine Chronik, nichts zum Nachschlagen. Ein Fremder, ein Ufer und seine Handschrift.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Vielleicht schreibt man Ihnen in einer Sprache, die Sie nie gelesen haben. Ein Tippen macht sie zu Ihrer; ein weiteres stellt die eigenen Worte wieder her, genau so, wie sie geschrieben wurden.",
  "What you keep": "Was bleibt",
  "A correspondence, not a chat.": "Ein Briefwechsel, kein Chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Hier scrollen Briefe nicht davon. Sie bleiben in einem Tagebuch aus Papier, in der Reihenfolge, in der das Meer sie brachte — Ihre auf der einen Seite, ihre auf der anderen, jeder mit dem Tag darunter, an dem er anlandete.",
  "You may give a stranger a private name, only for your own pages:": "Einem Fremden dürfen Sie einen eigenen Namen geben, nur für Ihre Seiten:",
  "the lighthouse keeper": "der Leuchtturmwärter",
  "the girl with the boat": "das Mädchen mit dem Boot",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Sie werden es nie erfahren. Und wenn eine Flasche von ihnen noch auf dem Wasser ist, sagt das Tagebuch es einfach und bittet Sie zu warten.",
  "The tide keeps its own time — and while you are here, so do you.": "Die Gezeiten haben ihre eigene Zeit — und solange Sie hier sind, haben Sie sie auch.",
  "Where you wake up": "Wo Sie aufwachen",
  "A real beach, and not one you picked.": "Ein wirklicher Strand — und keiner, den Sie ausgesucht haben.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Echte Küstenstücke an ihren echten Koordinaten — und Ihres fällt Ihnen durch Los zu. Der Sturm entscheidet, wo er Sie zurücklässt, und von jenem Morgen an ist es Ihr Zuhause. Das Licht darauf ist das Ihrer eigenen Stunde: öffnen Sie um Mitternacht, und Ihr Strand ist dunkel, die Sterne über dem Wasser. Keines davon ist eine Fotografie. Jede Welle zeichnet die App, Strich für Strich.",
  "The crossing": "Die Überfahrt",
  "You can watch it go.": "Sie können ihr nachsehen.",
  "your shore": "Ihr Ufer",
  "still at sea": "noch auf See",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Eine geworfene Flasche hinterlässt eine Linie auf der Karte, und die Linie wächst, während Sie schlafen. Der durchgezogene Teil ist die bereits gesegelte Strecke; die Striche voraus erscheinen erst, wenn Sie wissen, wer am anderen Ende wartet.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "Die Inseln der Fremden, deren Briefe Sie gelesen haben, bleiben für immer eingezeichnet — eine private Karte all jener, die das Meer Ihnen vorgestellt hat.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "Die Karte gehört der App selbst: Küstenlinien von Natural Earth, gemeinfrei, im Programm mitgeführt. Kein Kartendienst wird je aufgerufen, und nichts über Ihren Standort verlässt Ihre Hände.",
  "·": "·",
  "Privacy": "Datenschutz",
  "Support": "Support",
  "A bottle, thrown well, can reach anyone.": "Eine gut geworfene Flasche kann jeden erreichen.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Küstenlinien von Natural Earth (gemeinfrei). Klänge von freesound.org (CC0). Kein Kartendienst, kein Tracking, keine Cookies: Diese Seite weiß nicht, wer Sie sind — genau wie das Meer.",
  "The storm took the ship, the cargo, and every map you owned.": "Der Sturm nahm das Schiff, die Ladung und jede Karte, die du besaßest.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "Das Meer ließ dir dafür nur eines: einen Strand am Ende der Welt.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Man sagt, die Flut trage Worte anderer Schiffbrüchiger. Und dass eine gut geworfene Flasche jeden erreichen kann.",
  "Your new home": "Dein neues Zuhause",
  "A stranger": "Jemand Unbekanntes"
 },
 "pt-BR": {
  "Bottlegram — a slow messaging app": "Bottlegram — um app de mensagens lentas",
  "Skip to content": "Ir para o conteúdo",
  "How it works": "Como funciona",
  "Three bottles a day,": "Três garrafas por dia,",
  "and a whole sea in between.": "e um mar inteiro no meio.",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram é um aplicativo de mensageria lenta. Você não escreve para ninguém em particular — é a correnteza que decide com quem você vai conversar.",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "Um trecho de mar visto de cima: duas costas, e uma garrafa que vai de uma à outra.",
  "Your shore": "Sua praia",
  "Someone's shore": "A praia de alguém",
  "six to twenty-four hours": "de seis a vinte e quatro horas",
  "You throw a bottle": "Você lança uma garrafa",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "Todo dia o mar te deixa três garrafas. Você põe uma mensagem dentro e a entrega à correnteza, sem escolher para quem.",
  "Someone finds it": "Alguém a encontra",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "Horas depois ela encalha na praia de outro náufrago. Do mesmo modo, na sua areia chegam as garrafas dos outros.",
  "And answers, if they want to": "E responde, se quiser",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "Quem encontra sua carta pode responder, e daí nasce uma correspondência. Ninguém é obrigado: uma garrafa sem resposta é coisa que acontece no mar.",
  "The chart follows them": "A carta as acompanha",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "No mapa você acompanha as garrafas que lançou, e as que voltam para você das praias que já conhece.",
  "The waiting": "A espera",
  "The journal": "O diário",
  "The beaches": "As praias",
  "The chart": "A carta náutica",
  "A slow messaging app": "Um app de mensagens lentas",
  "The sea has no use for hurry.": "O mar não tem uso para a pressa.",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "Em algum lugar, um desconhecido está escrevendo para você. Sem nomes. Sem barulho. Só a maré, e o que ela decidir deixar na sua areia.",
  "Coming to the App Store": "Em breve na App Store",
  "Not out yet. The sea is still being tested.": "Ainda não saiu. O mar ainda está em testes.",
  "The shipwreck": "O naufrágio",
  "Sardegna, Italy": "Sardenha, Itália",
  "The point": "O ponto",
  "Everything here is slow,": "Aqui tudo é lento,",
  "and none of it is by accident.": "e nada disso é por acaso.",
  "You write, and then you wait.": "Você escreve, e então espera.",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "Uma carta demora o que demorar a água entre vocês. Uma praia no mesmo mar pode responder pela manhã; o outro lado do mundo vai fazer você esperar dias. Não há nada em que tocar para que chegue antes — e depois da primeira, você para de querer isso.",
  "The beach is empty, and it is yours.": "A praia está vazia, e é sua.",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "Ninguém está on-line. Ninguém está ausente. Ninguém está digitando, e nada é marcado como entregue, visto ou lido. Há uma praia, o som da água e um horizonte que não pede nada de você.",
  "You have all the time in the world to choose the words.": "Você tem todo o tempo do mundo para escolher as palavras.",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "Uma carta que custa alguma coisa é mais bem escrita. Aqui você não dispara sete seguidas, não se corrige uma hora depois e não pode chamar nenhuma de volta. Então você fica um tempo com ela, e diz o que é verdadeiro em vez do que é rápido.",
  "And the waiting turns out to be the good part.": "E a espera acaba sendo a melhor parte.",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "Os dias passam. Você faz outras coisas. Então a maré deixa na sua areia algo que ninguém programou, ninguém promoveu e ninguém poderia ter vendido para você — a letra de um desconhecido, de uma costa que você nunca viu.",
  "Somewhere to savour the quiet, while everything else is racing.": "Um lugar para saborear a quietude, enquanto todo o resto corre.",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "Aqui é manhã e o vento vem da terra. Não vou dizer meu nome, mas vou dizer que plantei três figueiras atrás de casa e uma pegou. Se esta garrafa chegar a algum lugar, escreva e me conte que tempo faz aí.",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "Todo dia a maré vai trazer garrafas de desconhecidos de todo o mar. Fale com gentileza — as palavras vão longe.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "O mar não tem uso para a pressa. Escreva para um desconhecido numa praia de verdade e deixe a maré levar dias para entregar — sem nomes, sem feeds, um app de iPhone para quem quer a espera de volta.",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "O mar não tem uso para a pressa. Escreva para um desconhecido numa praia de verdade e deixe a maré levar dias para entregar.",
  "Sections": "Seções",
  "A nautical chart with the route of a bottle across the open sea": "Uma carta náutica com a rota de uma garrafa pelo mar aberto",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "O app em Cala Goloritzé ao meio-dia: mar turquesa, areia clara e quatro garrafas na praia.",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "Uma correspondência no diário: a carta de um desconhecido a quem quem lê deu em particular o nome «Black sand», a resposta abaixo, e um aviso de que uma garrafa dele ainda está no mar.",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "A carta náutica: uma rota traçada de Cala Goloritzé para fora do Mediterrâneo e ao norte pelo Atlântico rumo à Islândia, com a garrafa no meio do caminho.",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "O amanhecer em Anse Source d'Argent como o app o desenha: um céu rosado, água calma, uma palmeira na areia.",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "O meio-dia em Cala Goloritzé como o app o desenha: céu azul, mar turquesa, garrafas na areia clara.",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "O entardecer em Reynisfjara como o app o desenha: um céu de brasas sobre a areia vulcânica preta.",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "A noite em Haukland Beach como o app a desenha: a aurora sobre um mar ártico escuro.",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "Ela gira sozinha: o amanhecer em La Digue, o meio-dia na Sardenha, o entardecer na areia preta de Reynisfjara e uma noite ártica com a aurora lá em cima. No app você ganha uma praia, e não é você que escolhe — que é o melhor disso.",
  "One of the 250 shores the storm knows. Yours could be any of them.": "Uma das 250 praias que a tempestade conhece. A sua pode ser qualquer uma.",
  "Vík, Iceland": "Vík, Islândia",
  "La Digue, Seychelles": "La Digue, Seicheles",
  "Lofoten, Norway": "Lofoten, Noruega",
  "Sintra, Portugal": "Sintra, Portugal",
  "One last thing": "Uma última coisa",
  "The tide is already on its way.": "A maré já está a caminho.",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "Numa praia que você nunca viu, um desconhecido está apertando a rolha de uma garrafa agora mesmo. O mar vai decidir em qual areia ela chega. Quem sabe na sua.",
  "Who you are here": "Quem você é aqui",
  "No name. No face.": "Sem nome. Sem rosto.",
  "A seal in wax.": "Um selo de lacre.",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "Cada náufrago imprime sempre o mesmo emblema no lacre — e neste mar isso é uma pessoa inteira: sem perfil, sem fotografia, sem histórico, nada para procurar depois. Um desconhecido, uma praia e a letra dele.",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "Pode ser que escrevam para você numa língua que você nunca leu. Um toque a transforma na sua; outro devolve as palavras deles exatamente como foram escritas.",
  "What you keep": "O que você guarda",
  "A correspondence, not a chat.": "Uma correspondência, não um chat.",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "Aqui as cartas não somem com a rolagem. Elas ficam num diário de papel, na ordem em que o mar as entregou — as suas de um lado, as dele do outro, cada uma com o dia em que chegou escrito embaixo.",
  "You may give a stranger a private name, only for your own pages:": "Você pode dar a um desconhecido um nome particular, só para as suas páginas:",
  "the lighthouse keeper": "o faroleiro",
  "the girl with the boat": "a moça do barco",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": ". Eles nunca vão saber. E quando uma garrafa deles ainda está na água, o diário simplesmente diz isso, e pede que você espere.",
  "The tide keeps its own time — and while you are here, so do you.": "A maré tem o tempo dela — e enquanto você estiver aqui, você também tem.",
  "Where you wake up": "Onde você acorda",
  "A real beach, and not one you picked.": "Uma praia de verdade, e não foi você que escolheu.",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. Trechos de costa reais nas coordenadas reais — e a sua vem por sorteio. A tempestade decide onde deixar você, e daquela manhã em diante é casa. A luz sobre ela é a da sua própria hora: abra à meia-noite e a sua praia está escura, com as estrelas sobre a água. Nenhuma delas é uma fotografia. Cada onda é desenhada pelo app, linha por linha.",
  "The crossing": "A travessia",
  "You can watch it go.": "Você pode vê-la partir.",
  "your shore": "sua praia",
  "still at sea": "ainda no mar",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "Uma garrafa que você lançou deixa uma linha na carta, e a linha cresce enquanto você dorme. O traço cheio é a distância já navegada; os tracejados à frente só aparecem quando você sabe quem espera do outro lado.",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "As ilhas dos desconhecidos cujas cartas você leu ficam marcadas para sempre — um mapa particular de todos que o mar apresentou a você.",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "A carta é do próprio app: costas do Natural Earth, de domínio público, carregadas dentro dele. Nenhum serviço de mapas é chamado, e nada sobre onde você está sai das suas mãos.",
  "·": "·",
  "Privacy": "Privacidade",
  "Support": "Suporte",
  "A bottle, thrown well, can reach anyone.": "Uma garrafa, bem lançada, pode alcançar qualquer um.",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "Costas do Natural Earth (domínio público). Sons do freesound.org (CC0). Sem serviço de mapas, sem rastreamento, sem cookies: esta página não sabe quem você é, exatamente como o mar.",
  "The storm took the ship, the cargo, and every map you owned.": "A tempestade levou o navio, a carga e todos os mapas que você tinha.",
  "The sea, in return, left you one thing: a beach at the end of the world.": "O mar, em troca, deixou uma coisa só: uma praia no fim do mundo.",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "Dizem que a maré traz palavras de outros náufragos. E que uma garrafa, bem lançada, pode alcançar qualquer um.",
  "Your new home": "Seu novo lar",
  "A stranger": "Um desconhecido"
 },
 "ja": {
  "Bottlegram — a slow messaging app": "Bottlegram — ゆっくり届くメッセージ",
  "Skip to content": "本文へ",
  "How it works": "遊びかた",
  "Three bottles a day,": "一日に三本、",
  "and a whole sea in between.": "あいだには、ひとつの海。",
  "Bottlegram is a slow messaging app. You do not write to anybody in particular — it is the current that decides who you end up talking to.": "Bottlegram は、ゆっくりとしたメッセージのやりとりをするアプリです。宛先はあなたが決めません。だれと話すことになるかは、潮が決めます。",
  "A stretch of sea seen from above: two coasts, and a bottle drifting from one to the other.": "上から見た海の一角。ふたつの岸と、その一方からもう一方へ流れていく瓶。",
  "Your shore": "あなたの岸",
  "Someone's shore": "だれかの岸",
  "six to twenty-four hours": "六時間から二十四時間",
  "You throw a bottle": "瓶をひとつ放つ",
  "Every day the sea leaves you three bottles. You put a message inside and hand it to the current, without choosing who gets it.": "海は毎日、三本の瓶を置いていきます。ことづてを入れて、宛先を選ばずに潮へゆだねます。",
  "Someone finds it": "だれかが拾う",
  "Hours later it washes up on another castaway's beach. In the same way, other people's bottles wash up on your sand.": "数時間ののち、べつの漂流者の浜へ流れ着きます。同じように、あなたの砂浜にも、ほかの人の瓶が届きます。",
  "And answers, if they want to": "気が向けば、返事が来る",
  "Whoever finds your letter can write back, and a correspondence begins. Nobody has to: a bottle that goes unanswered is a thing that happens at sea.": "手紙を拾った人は、返事を書くことができます。そこから文通がはじまります。返事は義務ではありません。答えのない瓶も、海ではよくあることです。",
  "The chart follows them": "海図が追いかける",
  "On the map you can watch the bottles you have thrown, and the ones travelling back to you from the shores you already know.": "地図では、あなたが放った瓶と、すでに知っている岸から戻ってくる瓶を見守れます。",
  "The waiting": "待つこと",
  "The journal": "日誌",
  "The beaches": "浜辺",
  "The chart": "海図",
  "A slow messaging app": "ゆっくり届くメッセージ",
  "The sea has no use for hurry.": "海に急ぎは要らない。",
  "Somewhere out there, a stranger is writing to you. No names. No noise. Only the tide, and whatever it decides to leave on your sand.": "どこかで、見知らぬ誰かがあなたに手紙を書いている。名前もなく、騒がしさもなく。あるのは潮と、それが砂に残していくものだけ。",
  "Coming to the App Store": "App Store にまもなく登場",
  "Not out yet. The sea is still being tested.": "まだ公開前です。海はいま試験中。",
  "The shipwreck": "難破",
  "Sardegna, Italy": "サルデーニャ、イタリア",
  "The point": "要するに",
  "Everything here is slow,": "ここでは何もかもが遅い。",
  "and none of it is by accident.": "そのどれもが、偶然ではない。",
  "You write, and then you wait.": "書いて、それから待つ。",
  "A letter takes as long as the water between you takes. A shore across the same sea might answer by morning; the far side of the world will keep you waiting for days. Nothing you can tap will make it come sooner — and after the first one, you stop wanting it to.": "手紙は、あいだにある水の分だけ時間がかかる。同じ海の向こう岸なら朝には返事が来るかもしれないし、地球の裏側なら何日も待たされる。早く着かせるために押せるものは何もない。そして最初の一通のあとは、押したいとも思わなくなる。",
  "The beach is empty, and it is yours.": "浜辺には誰もいない。そしてそれはあなたのものだ。",
  "Nobody is online. Nobody is away. Nobody is typing, and nothing is marked delivered, seen or read. There is a shore, the sound of the water, and a horizon that asks nothing of you at all.": "誰もオンラインではない。誰も離席していない。誰も入力中ではなく、送信済みも既読もない。あるのは岸と、水の音と、何ひとつ求めてこない水平線だけ。",
  "You have all the time in the world to choose the words.": "言葉を選ぶ時間なら、いくらでもある。",
  "A letter that costs something is written better. You will not fire off seven in a row here, you will not correct yourself an hour later, and you cannot call one back. So you sit with it a while, and you say the true thing instead of the quick one.": "手間のかかる手紙のほうが、うまく書ける。ここでは七通を続けざまに送ることもなく、一時間後に言い直すこともなく、送ったものを取り消すこともできない。だからしばらく手元に置いて、早い言葉ではなく本当の言葉を書く。",
  "And the waiting turns out to be the good part.": "そして待つ時間こそが、いちばんいいところだと分かる。",
  "Days pass. You do other things. Then the tide leaves something on your sand that nobody scheduled, nobody promoted and nobody could have sold you — a stranger's handwriting, from a coast you have never seen.": "日が過ぎる。ほかのことをして暮らす。するとある日、潮が砂に何かを置いていく。誰も予定せず、誰も宣伝せず、誰にも売ることのできなかったもの——見たこともない海岸から届いた、知らない誰かの手書きの文字だ。",
  "Somewhere to savour the quiet, while everything else is racing.": "ほかのすべてが走りつづけるあいだ、静けさを味わえる場所。",
  "Here it is morning and the wind comes off the land. I will not tell you my name, but I will tell you that I planted three fig trees behind the house and one of them took. If this bottle lands anywhere at all, write and tell me the weather where you are.": "こちらは朝で、風は陸から吹いてくる。名前は明かさないけれど、家の裏にいちじくを三本植えて、そのうち一本が根づいたことは伝えておく。この瓶がどこかに着いたら、そちらの天気を書いて送ってほしい。",
  "Every day the tide will bring bottles from strangers across the sea. Speak kindly — words travel far.": "毎日、潮が海じゅうの見知らぬ人たちの瓶を運んでくる。やさしい言葉を。言葉は遠くまで行く。",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it — no names, no feeds, an iPhone app for people who want the waiting back.": "海に急ぎは要らない。実在する浜辺にいる見知らぬ誰かへ手紙を書き、潮が何日もかけて運ぶのにまかせる。名前もフィードもない、待つ時間を取り戻したい人のための iPhone アプリ。",
  "The sea has no use for hurry. Write to a stranger on a real beach and let the tide take days to carry it.": "海に急ぎは要らない。実在する浜辺にいる見知らぬ誰かへ手紙を書き、潮が何日もかけて運ぶのにまかせる。",
  "Sections": "セクション",
  "A nautical chart with the route of a bottle across the open sea": "外洋を渡る瓶の航路を記した海図",
  "The app at Cala Goloritzé at midday: turquoise sea, pale sand, and four bottles washed up on the shore.": "正午のカーラ・ゴロリッツェのアプリ画面。ターコイズの海、明るい砂、岸に打ち上げられた四本の瓶。",
  "A correspondence in the journal: a letter from a stranger the reader has privately named Black sand, the reply underneath, and a note saying a bottle of theirs is still at sea.": "日誌のなかの文通。読み手が心のなかで「Black sand」と名づけた相手からの手紙、その下に返信、そして相手の瓶がまだ海の上にあることを告げる一行。",
  "The nautical chart: a route drawn from Cala Goloritzé out of the Mediterranean and north across the Atlantic towards Iceland, with the bottle partway along it.": "海図。カーラ・ゴロリッツェから地中海を出て、大西洋を北上しアイスランドへ向かう航路。瓶はその途中にいる。",
  "Dawn at Anse Source d'Argent, as the app draws it: a rose sky, calm water, a palm on the sand.": "アプリが描くアンス・スルス・ダルジャンの夜明け。薔薇色の空、静かな水、砂の上の一本のやし。",
  "Midday at Cala Goloritzé, as the app draws it: blue sky, turquoise sea, bottles on the pale sand.": "アプリが描くカーラ・ゴロリッツェの正午。青い空、ターコイズの海、明るい砂の上の瓶。",
  "Dusk at Reynisfjara, as the app draws it: an ember sky over black volcanic sand.": "アプリが描くレイニスフィヤラの夕暮れ。黒い火山砂の上に、燠火のような空。",
  "Night at Haukland Beach, as the app draws it: the aurora over a dark arctic sea.": "アプリが描くハウクラン・ビーチの夜。暗い北極の海の上を渡るオーロラ。",
  "It turns by itself: dawn at La Digue, midday in Sardegna, dusk on the black sand of Reynisfjara, and an arctic night with the aurora overhead. In the app you get one shore, and you do not choose it — which is the best thing about it.": "ひとりでに移り変わる。ラ・ディーグの夜明け、サルデーニャの正午、レイニスフィヤラの黒い砂の夕暮れ、そして頭上をオーロラが渡る北極の夜。アプリでは一つの浜だけが与えられ、それを選ぶことはできない——そこがいちばんいいところだ。",
  "One of the 250 shores the storm knows. Yours could be any of them.": "嵐が知っている250の浜辺のひとつ。あなたの浜は、そのどれかもしれない。",
  "Vík, Iceland": "ヴィーク、アイスランド",
  "La Digue, Seychelles": "ラ・ディーグ、セーシェル",
  "Lofoten, Norway": "ロフォーテン、ノルウェー",
  "Sintra, Portugal": "シントラ、ポルトガル",
  "One last thing": "最後にひとつ",
  "The tide is already on its way.": "潮はもう動きはじめている。",
  "On a shore you have never seen, a stranger is pushing the cork into a bottle right now. The sea will decide whose sand it touches next. Maybe yours.": "見たこともない岸辺で、いままさに見知らぬ誰かが瓶にコルクを押し込んでいる。次にどの砂に届くかは海が決める。もしかしたら、あなたの砂に。",
  "Who you are here": "ここでのあなた",
  "No name. No face.": "名前もなく、顔もない。",
  "A seal in wax.": "あるのは蝋の封印だけ。",
  "Every castaway presses the same emblem into the wax, always — and on this sea that is the whole of a person: no profile, no photograph, no history, nothing to look up afterwards. A stranger, a shore, and their handwriting.": "どの漂流者も、いつも同じ紋章を蝋に押す。この海では、それが人のすべてだ。プロフィールも、写真も、履歴もなく、あとから調べられるものは何もない。見知らぬ誰かと、ひとつの岸と、その手書きの文字だけ。",
  "They may be writing to you in a language you have never read. One tap turns it into yours; another puts their own words back, exactly as they wrote them.": "読んだことのない言語で書かれてくるかもしれない。ひと押しで自分の言葉になり、もうひと押しで、書かれたとおりの言葉に戻る。",
  "What you keep": "手元に残るもの",
  "A correspondence, not a chat.": "チャットではなく、文通。",
  "Letters do not scroll away here. They stay in a journal made of paper, in the order the sea delivered them — yours on one side, theirs on the other, each with the day it came ashore written underneath.": "ここでは手紙が流れて消えたりしない。紙の日誌に、海が届けた順のまま残る。自分のものは片側に、相手のものは反対側に、それぞれの下に岸へ着いた日が書かれている。",
  "You may give a stranger a private name, only for your own pages:": "見知らぬ相手には、自分の日誌のなかだけで通じる名前をつけられる。",
  "the lighthouse keeper": "灯台守",
  "the girl with the boat": "舟をもつ娘",
  ". They will never know it. And when a bottle of theirs is still out on the water, the journal simply says so, and asks you to wait.": "。相手がそれを知ることはない。相手の瓶がまだ海の上にあるときは、日誌がそう告げて、待つように言うだけだ。",
  "The tide keeps its own time — and while you are here, so do you.": "潮には潮の時間がある。そしてここにいるあいだは、あなたにも。",
  "Where you wake up": "目を覚ます場所",
  "A real beach, and not one you picked.": "本物の浜辺。しかも、自分で選んだのではない。",
  "Cala Goloritzé. Reynisfjara. Anse Source d'Argent. True stretches of coast at their true coordinates — and yours is drawn by lot. The storm decides where it leaves you, and from that morning on it is home. The light on it is the light of your own hour: open it at midnight and your beach is dark, with the stars out over the water. Not one of these is a photograph. Every wave is drawn by the app, line by line.": "カーラ・ゴロリッツェ。レイニスフィヤラ。アンス・スルス・ダルジャン。実在する海岸を、実在する座標のままに。そして自分の浜は、くじで決まる。どこに打ち上げるかを決めるのは嵐で、その朝からそこが家になる。射す光はあなたのいまの時刻の光だ。真夜中に開けば浜は暗く、水の上に星が出ている。どれも写真ではない。波の一本一本を、アプリが線で描いている。",
  "The crossing": "航路",
  "You can watch it go.": "旅立っていくのを、見ていられる。",
  "your shore": "あなたの岸",
  "still at sea": "まだ海の上",
  "A bottle you have thrown leaves a line on the chart, and the line grows while you sleep. The solid part is the distance already sailed; the dashes ahead appear only once you know who is waiting at the far end.": "投げた瓶は海図に一本の線を残し、その線は眠っているあいだも伸びていく。実線はすでに渡った距離。その先の破線は、向こう岸で誰が待っているかを知ってからでないと現れない。",
  "The islands of strangers whose letters you have read stay marked there for good — a private map of everyone the sea has introduced you to.": "手紙を読んだ相手の島は、そのまま海図に残りつづける。海が引き合わせてくれた人たちだけの、自分だけの地図になる。",
  "The chart is the app's own: coastlines from Natural Earth, public domain, carried inside it. No map service is ever called, and nothing about where you are leaves your hands.": "海図はアプリ自身のものだ。海岸線はパブリックドメインの Natural Earth を内部に持っている。地図サービスを呼ぶことは一度もなく、あなたの居場所に関する情報が手元から出ていくこともない。",
  "·": "·",
  "Privacy": "プライバシー",
  "Support": "サポート",
  "A bottle, thrown well, can reach anyone.": "うまく投げた瓶は、誰のもとにも届きうる。",
  "Coastlines from Natural Earth (public domain). Sounds from freesound.org (CC0). No map service, no tracking, no cookies: this page does not know who you are, exactly like the sea.": "海岸線は Natural Earth（パブリックドメイン）。音は freesound.org（CC0）。地図サービスも、追跡も、Cookie もない。このページはあなたが誰かを知らない——海とまったく同じように。",
  "The storm took the ship, the cargo, and every map you owned.": "嵐が船を、荷を、持っていた海図のすべてを奪った。",
  "The sea, in return, left you one thing: a beach at the end of the world.": "代わりに海が残したものはひとつ — 世界の果ての浜。",
  "They say the tide brings words from other castaways. And that a bottle, thrown well, can reach anyone.": "潮はほかの漂流者の言葉を運ぶという。うまく投げた瓶は、誰にでも届くという。",
  "Your new home": "あなたの新しい住まい",
  "A stranger": "見知らぬ誰か"
 }
};
const INVARIATE = [",", "Bottlegram", "N", "bottlegram@bulbmode.com", "Cala Goloritzé", "Reynisfjara", "Anse Source d'Argent", "Haukland Beach", "Praia da Ursa"];
